### ISSUE TITLE
Home: Adjust focus area title styling 

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#102]
Use heading three styling for "Join us. Help us protect:"

Untitled Serif 
font-size: 32px
line-height: 40px 

![image](https://user-images.githubusercontent.com/6118778/40380376-ec064f32-5dc6-11e8-800d-ff90f7247765.png)

https://live-aldf-wp.pantheonsite.io/

**Comment by tedw** [comment]
I think Mat didn’t have that font installed at first so thought that's what the text should look like 😆 

Fixed now.

**Comment by jamielyn** [comment]
:koala:
