### ISSUE TITLE
Engaging Networks Wrapper

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#103]
@tedw More info on Engaging Networks:

**IMPORTANT: The "ALDF Bootstrap Template" and all forms are LIVE on aldf.org, so no changes should be made directly to those items. Copies should be made.**

The clientdev@threespot.com account that's store in 1password now has access to all the ALDF donation templates and forms. From what I can tell from poking around, all the forms are using the same "ALDF Bootstrap Template" so we need to create a new version of that template with updated styles (colors, typefaces, logo and then let's see where we are). 

We will need to also figure out the best approach for going live -- do we create duplicates of all the forms using the new template and just wait to push them live at launch? Can they be live now if they're only linked to the new site? OR do we need to update the existing forms with the new template? 🤔 

cc @matbrady @Henryhankdc

**Comment by tedw** [comment]
We will create a new "theme" that can be applied to the old donation form page once the new site is live. We will test using this copy https://give.aldf.org/page/5457/donate/1

**Comment by lizzycederberg** [comment]
We need to apply styles to the form itself. David let us know that the page we've been working in includes an example of every element they will want to use: (Threespot)

They will also be using the Email to Target type ([example](https://act.aldf.org/page/5687/action/1?mode=DEMO)) and I would like to see if we can apply any light styling to those too. 

@tedw @Henryhankdc

**Comment by tedw** [comment]
@Henryhankdc I can work on this so you can focus on Children’s

**Comment by tedw** [comment]
I created a demo page with all of the fields David added:
https://dev-aldf-wp.pantheonsite.io/donation/

**Comment by tedw** [comment]
Here is a preview https://live-aldf-wp.pantheonsite.io/donate/

Ready for VQA (but there isn't a whole lot more we can do)

**Comment by lizzycederberg** [comment]
@tedw Now that VQA is done, please update the template in EN.

**Comment by tedw** [comment]
Updated https://give.aldf.org/page/5681/donate/1?mode=DEMO

**Comment by lizzycederberg** [comment]
@tedw I sent David that link and the CSS is not loading for him. This is what he's seeing in two browsers:
![image003](https://user-images.githubusercontent.com/13699106/41612014-9e47f390-73bf-11e8-9edf-6f5d26094872.jpg)

Error
![image002](https://user-images.githubusercontent.com/13699106/41612021-a176d04a-73bf-11e8-901f-562391727192.png)

**Comment by tedw** [comment]
Right, so the CSS filename is going to change every time we deploy, which is why it broke. I'm deploying a fix to try to allow 3rd-parties to link to assets without the unique ID at the end.

FYI, that other error `$ is not defined` is from their GTM code. They are running some code via GTM that expects jQuery to be on the page but we’re not using jQuery on the new site. I think I already talked to @LizLord about this. That code won’t be necessary once the new site launches so we just need to remember to remove it.

**Comment by tedw** [comment]
Fixed https://give.aldf.org/page/5457/donate/1?mode=DEMO

**Comment by lizzycederberg** [comment]
Ok -- quick question. Is the smaller text (third paragraph) supposed to be in one column like this:

![screen shot 2018-06-19 at 3 57 48 pm](https://user-images.githubusercontent.com/13699106/41621043-8cc57006-73d9-11e8-81cc-45c50e0bf479.png)

**Comment by tedw** [comment]
That all depends on how David adds the content in EN. We don't have control over that.
