### ISSUE TITLE
Claim site in GSC

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#107]
@LizLord Please claim the site in Search Console. It will be moving from `http` > `https` at launch. 

Note: When we go live there will be two domains `aldf.org` and `shop.aldf.org`

The shop currently lives here: https://www.cafepress.com/aldf

**Comment by LizLord** [comment]
@lizzycederberg 
in re: my earlier comment - ALDF already has a GTM account on their current aldf.org site. Please request access to that w/ publish permissions too which will allow us to claim the site in Search Console and prepare for tagging the new site.

**Comment by lizzycederberg** [comment]
@LizLord David said he's made us Editors and added us to GTM. Can you please validate?

**Comment by LizLord** [comment]
@lizzycederberg 
GTM and GA access is confirmed for http://aldf.org but not the cafepress.com/aldf site. 
Google Search Console verification failed - the GTM container code is in the wrong place on the site and Google won't confirm. (this is actually a really good thing so no one else can de-index your site)
We'll need to verify both the sites with alternate method. The options available to us include:

a. upload an HTML verification file
b. Add a meta tag to the site's homepage
c. Sign into the Domain Provider for the site

Let me know the preferred path forward from here!

**Comment by lizzycederberg** [comment]
Ok I will talk to the client about these options today!

**Comment by lizzycederberg** [comment]
@LizLord So apparently Cafepress is not going to make this easy and none of the three options you outlined will be feasible. What's the downside of not claiming the site ahead of launch?

Also, for reference in this ticket, our new launch date is **July 2nd**

**Comment by LizLord** [comment]
@lizzycederberg let's drop it for the cafepress site - impact there is minimal, but be sure to get this for ALDF.org - the GSC verification failed for the main site because while GTM added to the site it is not in the expected location. We'll need to verify ALDF.org in Google Search Console with one of the 3 options in the earlier comment.

**Comment by lizzycederberg** [comment]
@LizLord They want to go with option 1 or 2. Can you please share whichever file they need to upload? Thanks!

**Comment by LizLord** [comment]
@lizzycederberg 
**Option 1**
Steps 1 and 2 to be completed by ALDF
Steps 3 and 4 to be completed by Threespot
![image](https://user-images.githubusercontent.com/16021927/41249239-8de5be7c-6d81-11e8-939e-2537aa2e29e1.png)
HTML file contents:
```
google-site-verification: googlee60f3fe904ed83b1.html
```

--OR--

**Option 2**
Step 1 to be completed by ALDF
Step 2 to be completed by Threespot
![image](https://user-images.githubusercontent.com/16021927/41249404-0d9d01b6-6d82-11e8-9a31-87816ac0df16.png)

`<meta name="google-site-verification" content="bhpnwIihdEBU3O1OesFs_OufKc8J_vSZH63FlL2kyOo" />`

**Comment by lizzycederberg** [comment]
@LizLord HTML file was uploaded: http://aldf.org/googlee60f3fe904ed83b1.html

Can you please take a look and let me know if you have everything you need to claim the site?

**Comment by LizLord** [comment]
@lizzycederberg Confirmed! Site verification worked and we now have the http version of the ALDF site claimed in Google Search Console. 
At launch, we'll want to file a 'change of address' with Google which will transfer the SEO identity from the old site to the new https site.
