### ISSUE TITLE
Add GTM container 

### ISSUE THREAD

**Issue by LizLord** [Threespot/aldf-wp#109]
[No action yet - waiting for account access/confirmation for container GTM-5NG4QP]

**Comment by LizLord** [comment]
Add container GTM container GTM-5NG4QP to the new site

**Comment by LizLord** [comment]
@lizzycederberg Will you inform ALDF / check on the purpose behind the additional GTM containers that are on the current ALDF site? If they're tracking anything important there we'll want to plan to migrate those tags to the main container. Only one GTM container is recommended on any site. 

Main - GTM-5NG4QP (we have access) ✅ (no questions)
Other - GTM-PV2GWJ (homepage - no access) - is this necessary?
Other - GTM-T5QLZ74 (donation pages - no access) - this may belong to their donation platofrm

**Comment by tedw** [comment]
There is now a field for the GTM key in the admin
https://live-aldf-wp.pantheonsite.io/wp/wp-admin/admin.php?page=aldf-info
