### ISSUE TITLE
Pagination broken on Search Articles

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#112]
http://live-aldf-wp.pantheonsite.io/articles/

Navigating to any of the pagination options results in an unstyled error apge:

![stylemejesus](https://user-images.githubusercontent.com/6942589/40789381-45186f38-64c0-11e8-8026-7879a2b7fe68.png)

**Comment by tedw** [comment]
Was due to typo, fixed now.

**Comment by lfrancis** [comment]
Confirmed addressed
