### ISSUE TITLE
Components fail validation

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#113]
https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/ fails validation at https://validator.w3.org/nu/?doc=https%3A%2F%2Flive-aldf-wp.pantheonsite.io%2Farticle%2Ftest-article-with-components%2F

Many of these are FOL, but there are a few that seem worth examining.

**Comment by lfrancis** [comment]
Do we not care about line 6:

`Error: Bad value  for attribute id on element h5: An ID must not be the empty string.`
`From line 389, column 1; to line 389, column 10`
`llat.</p>↩<h5 id=""></h5>↩`

**Comment by tedw** [comment]
This is a content-entry issue. The client needs to delete the empty heading in the wysiwyg editor.

**Comment by rmundstock** [comment]
Removed the empty heading

**Comment by lizzycederberg** [comment]
@lfrancis Can you please review?

**Comment by lfrancis** [comment]
Confirmed addfressed
