### ISSUE TITLE
404 VQA

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#115]
On mobile, can we move the search button up, so it stays in line with the field? This way it will match the mobile search listing page. 

http://live-aldf-wp.pantheonsite.io/404

Dev
![image](https://user-images.githubusercontent.com/6118778/40805478-5f4c823c-64ec-11e8-93bf-5a816f5fbb8d.png)

Search listing 
![image](https://user-images.githubusercontent.com/6118778/40805452-50400e1c-64ec-11e8-8017-762f21fa84e5.png)

http://live-aldf-wp.pantheonsite.io/?s=search+term&taxonomy_focus_area=&taxonomy_how_we_work=&date_range=&post_type=

**Comment by tedw** [comment]
Updated

**Comment by jamielyn** [comment]
:hatched_chick:
