### ISSUE TITLE
Cookie alert

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#116]
@tedw David asked us to add one of those alerts to the site that would appear when users first arrive to tell them the site uses cookies. 

I'm wondering if it's possible to reuse the top-hat alert, but make it really low profile and small?

He also asked if there's a way to do this with a plugin, because he wants it on their current site too.

**Comment by lizzycederberg** [comment]
@tedw We need to add this to the new site.

**Comment by tedw** [comment]
@lizzycederberg I need the following:

- Design (should consider both with and without the donation promo)
- Logic for showing it (i.e. does it ever reset or do we hide it forever once a user dismisses it?)

Once I have that, I can add it and provide a field in the admin for ALDF to edit the text.

**Comment by lizzycederberg** [comment]
@cmontwill Can you please provide a design for this? Should be a very simple treatment. It also must require the user to actively accept in order to remove it.

**Comment by lizzycederberg** [comment]
@tedw Once someone accepts this, it does not need to appear again

**Comment by cmontwill** [comment]
![screen shot 2018-06-28 at 11 14 36 am](https://user-images.githubusercontent.com/5890745/42043503-a08578e2-7ac4-11e8-80f7-261e58a610ee.png)
@ted will this work? It will anchor to the bottom and stretch to the full width of the screen.

**Comment by tedw** [comment]
Deployed
