### ISSUE TITLE
Component lacks padding/margin in mobile render

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#119]
https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/

This component lacks padding/margin in mobile render:

![img_d43822d7cfc6-1](https://user-images.githubusercontent.com/6942589/40845377-84ea10a2-6584-11e8-81ad-101a3e20b2f1.jpeg)

**Comment by tedw** [comment]
This ended up requiring a major refactor to allow reusable components to be placed in any layout. Would be good to do a regression test of each page type.

**Comment by lfrancis** [comment]
Confirmed addressed
