### ISSUE TITLE
Live site- Recent news missing featured

### ISSUE THREAD

**Issue by lfhello** [Threespot/aldf-wp#121]
@tedw 

On this link https://live-aldf-wp.pantheonsite.io/case/kristen-lindsey/

The **featured news article doesn't show up on desktop**, but shows up on mobile with an image. 

Mobile- featured and then the two secondary articles
![screen shot 2018-06-04 at 9 48 13 am](https://user-images.githubusercontent.com/17705791/40921120-96bc47fa-67dc-11e8-8293-56636f9bfef0.png)

Desktop- two secondary articles only...
![screen shot 2018-06-04 at 9 48 22 am](https://user-images.githubusercontent.com/17705791/40921136-a09fec9a-67dc-11e8-84d3-ca2da983a9b8.png)

**Comment by tedw** [comment]
Great catch! This was happening in all related news components other than the homepage. Fixed now.

**Comment by tedw** [comment]
There is now a field for the GTM key in the admin
https://live-aldf-wp.pantheonsite.io/wp/wp-admin/admin.php?page=aldf-info

**Comment by lfhello** [comment]
Thanks, @tedw !

I just realized the first yellow line isn't necessary in mobile- can we remove that and move up the first image/ headline?

The lines are really just dividers at this point, so we don't need it for the first story because there will be some spacing under Recent News and then the first image/ headline can start


![screen shot 2018-06-04 at 4 48 07 pm](https://user-images.githubusercontent.com/17705791/40940923-4be2d358-6817-11e8-8773-a54af8e9bd37.png)

**Comment by tedw** [comment]
Updated

**Comment by lfhello** [comment]
wonderful! :octocat:
