### ISSUE TITLE
Allow admin to edit Take Over reset date

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#128]
@tedw ALDF wants to be able to manage how long it takes to reset the take over/top hat promo once someone has dismissed it. I think you have it set for 60 days right now. Can we make this a field in the CMS?

**Comment by tedw** [comment]
Sure

**Comment by tedw** [comment]
There is now a field for this in the Donation Promo section on the homepage
https://live-aldf-wp.pantheonsite.io/wp/wp-admin/post.php?post=62&action=edit
