### ISSUE TITLE
Create How We Work content type

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#129]
- Hero should be styled like the Focus Area hero with page title and subtitle
- Will need to add the "Share" icons somewhere
- All other content fields should borrow from the Issue template
- These pages will serve as the landing page for each of the How We Work nav items -- every Work Type should appear in the navigation, so if that changes the recommendation to make the pages manually, that's ok
- Admin will create a Work Type and then a page using the same title and slug

**Comment by lizzycederberg** [comment]
@tedw Here's a comp for how to incorporate the Share icons

![sharereco](https://user-images.githubusercontent.com/13699106/41302730-3dd84ca2-6e39-11e8-9a7e-f30cd66b5622.png)

**Comment by tedw** [comment]
Added “How We Work” custom post type and integrated with main nav. Supports same fields as Issue pages but with custom hero billboard.
