### ISSUE TITLE
Allow admins to pull in any page in Resources

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#130]
In the 2-up Related Content component, ALDF does not want to limit the Resources to documents. They want to use it to create a list of any content that they consider to be a resource. Can we update this component?

**Comment by tedw** [comment]
You can now add the following content types as Resources in the 2-up Related Content component:

- Action
- Article
- Case
- Document
- External Link
- Focus Area
- Issue
- Page
- Project

**Comment by lizzycederberg** [comment]
Looks good!
