### ISSUE TITLE
EN form spacing issues

### ISSUE THREAD

**Issue by cmontwill** [Threespot/aldf-wp#131]
https://live-aldf-wp.pantheonsite.io/donate/

1. Create a bottom margin on the gift buttons and donation amounts on mobile (should be that same as the margin on the right side)
![screen shot 2018-06-12 at 12 37 46 pm](https://user-images.githubusercontent.com/5890745/41305492-175fdfec-6e41-11e8-9034-4923abb7e13e.png)

2.Create the same padding on top of the dog image as the bottom on mobile
![screen shot 2018-06-12 at 12 37 43 pm](https://user-images.githubusercontent.com/5890745/41305496-1c4ed4c2-6e41-11e8-98eb-1adc8df72c41.png)

**Comment by tedw** [comment]
Updated

**Comment by cmontwill** [comment]
Spacey 👩‍🚀
