### ISSUE TITLE
External link shortcode

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#134]
https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/

**Comment by lfhello** [comment]
![screen shot 2018-06-14 at 9 03 51 am](https://user-images.githubusercontent.com/17705791/41471591-15ca28ca-7082-11e8-9e04-906fdb183e86.png)

**Comment by tedw** [comment]
Shortcode added, ready for VQA

**Comment by lfhello** [comment]
@tedw can you share where you put this?

**Comment by tedw** [comment]
@lfhello Someone needs to add the shortcodes to a test article. I only tested locally.
https://live-aldf-wp.pantheonsite.io/wp/wp-admin/post.php?post=3875&action=edit

Shortcode format is `[link id="123"]`. I added a column with the ID number in all of the listing pages for content that can be included this way (see #135).

CC: @rmundstock

**Comment by lizzycederberg** [comment]
@tedw I created a test on this page: https://live-aldf-wp.pantheonsite.io/wp/wp-admin/post.php?post=3875&action=edit

But I can't add an image to the link. When I click on the Featured Image, it says no media found -- but only when trying to do this on a link

![screen shot 2018-06-18 at 12 19 06 pm](https://user-images.githubusercontent.com/13699106/41548804-f5f3f90a-72f1-11e8-86cd-5094e5742288.png)

**Comment by tedw** [comment]
Rachel noticed that this morning and I have a fix ready to deploy.

**Comment by tedw** [comment]
Deployed

**Comment by lizzycederberg** [comment]
@lfhello Example with image in here: https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/

**Comment by lfhello** [comment]
@lizzycederberg @tedw 

Thanks!

So it looks like the one without an image is overlapping an image:

![screen shot 2018-06-18 at 2 10 54 pm](https://user-images.githubusercontent.com/17705791/41554017-8c6289ec-7301-11e8-8d53-1d26bfbdfc4e.png)

And on mobile, can we tighten the space below both of them to match what it is on top? It's much larger spacing below them right now just on mobile

![screen shot 2018-06-18 at 2 11 04 pm](https://user-images.githubusercontent.com/17705791/41554032-9c5dacbe-7301-11e8-8fec-13b7fc55ec51.png)


![screen shot 2018-06-18 at 2 10 43 pm](https://user-images.githubusercontent.com/17705791/41554029-9972c1ba-7301-11e8-8ce6-2f296f6cd5b6.png)

**Comment by tedw** [comment]
@lfhello Good catch! That's an easy fix.

**Comment by tedw** [comment]
Update deployed

**Comment by lfhello** [comment]
Awesome, thanks, @tedw 

Looks like the extra margin is still showing up on mobile- when I removed the 2em bottom margin, it seemed to fix it. Don't know how you want to adjust that

**Comment by tedw** [comment]
@lfhello Actually, I'm not seeing this issue. Can you test again and maybe clear your cache?

**Comment by tedw** [comment]
Sorry, was only looking at desktop. Fixed now, waiting on deployment.

**Comment by tedw** [comment]
Updated

**Comment by lizzycederberg** [comment]
@lfhello Can you take a look and close this if it's ok?

**Comment by lfhello** [comment]
yup- looks good!
