### ISSUE TITLE
Press Release Contact area

### ISSUE THREAD

**Issue by lfhello** [Threespot/aldf-wp#136]
@tedw - @rmundstock and I had worried about this before it got built and I just noticed it here
https://live-aldf-wp.pantheonsite.io/article/winter-weather-advisory-keep-animals-safe-warm-winter/
Is there any way to resolve this where it does not happen to Contact?

![screen shot 2018-06-18 at 8 08 54 am](https://user-images.githubusercontent.com/17705791/41535078-04751b6c-72cf-11e8-9c98-ebd677931fdf.png)

**Comment by lfhello** [comment]
It'd be weird to also happen to the "("

I'd rather it not be there for press releases. Or we see if they can write it differently? eh.

**Comment by lfhello** [comment]
@lizzycederberg @cmontwill maybe you guys have an idea?

**Comment by tedw** [comment]
Can you provide your ideal logic for this component? For example, alway use first letter on Article pages but not on Press Releases.

I can disable it for any particular article type (e.g. Press Releases), but beyond that, we would need to add a checkbox to the admin to disable the drop cap, or disable it by default and require a shortcode to apply it. Neither of those seem like great options.

There is also a hacky solution, which is to add `<p></p>` before the first line of text. The drop cap CSS only applies to the first paragraph tag, so adding the empty one means it won’t do anything to the following paragraph.

**Comment by lizzycederberg** [comment]
@tedw @lfhello There is a ticket open already where the client asked us to get rid of the large first letter for press releases #33
