### ISSUE TITLE
Solution for blank "Focus Area" or "How We Work"

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#139]
Some content does not have a Focus Area and a How We Work taxonomy, and it looks like something's missing when one is left blank

![screen shot 2018-06-19 at 3 41 15 pm](https://user-images.githubusercontent.com/13699106/41620319-5626a81e-73d7-11e8-9b28-26a8668681af.png)

Example seen here: https://live-aldf-wp.pantheonsite.io/article/the-legal-process-in-the-united-states-a-civil-case/

@cmontwill What would you suggest? cc @tedw

**Comment by cmontwill** [comment]
@tedw if the focus area is blank can we hide it like this: Also, it looks like there is took much top margin on this component, can we reduce it by half?

![screen shot 2018-06-19 at 9 51 43 am](https://user-images.githubusercontent.com/5890745/41672988-71fa4c1e-7489-11e8-941c-bee00819c71d.png)

**Comment by tedw** [comment]
Yup, we can do that. I think extra margin is the result of some layout refactoring I did the other week to fix issues with full-width page-builder components—will fix.

**Comment by tedw** [comment]
Ready for testing

**Comment by cmontwill** [comment]
Looks like that might have had some side effects on pages like the below. Is that true?
https://live-aldf-wp.pantheonsite.io/article/world-oceans-day-highlights-lack-of-protection-for-sea-life/
<img width="976" alt="screen shot 2018-06-22 at 2 06 23 pm" src="https://user-images.githubusercontent.com/5890745/41792007-7de8c9b8-7625-11e8-8432-da25c2046f86.png">

**Comment by tedw** [comment]
I had to clear the cache, seems fine now.

**Comment by cmontwill** [comment]
gotcha. good here.
