### ISSUE TITLE
Too much space between components

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#141]
@cmontwill Can you make a recommendation on the padding that should appear when the "How We Work / Focus Area" item appears directly above "Related" content -- Elizabeth feels it's way to large of a gap.

Example here: https://live-aldf-wp.pantheonsite.io/article/the-legal-process-in-the-united-states-a-civil-case/

![screen shot 2018-06-19 at 3 45 25 pm](https://user-images.githubusercontent.com/13699106/41620530-fc554358-73d7-11e8-8b41-c727c533e4f7.png)

cc @tedw

**Comment by cmontwill** [comment]
@ted can we reduce the top margin from 120 to 40 here. See attached.
![screen shot 2018-06-20 at 12 54 11 pm](https://user-images.githubusercontent.com/5890745/41672883-1776d33e-7489-11e8-91fe-a4fcfed65742.png)

**Comment by tedw** [comment]
Just noticed an issue with my fix on some pages without page-builder components. Deploying another 
update.

**Comment by tedw** [comment]
Ready for testing.

NOTE: Some pages have extra empty `<p>` tags at the end which creates extra space. ALDF should delete that.

**Comment by lizzycederberg** [comment]
Looking good
