### ISSUE TITLE
Button font does not match design

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#143]

**Comment by tedw** [comment]
Can you please provide more information (page URL, browser info, screenshot)? I would also recommend clearing your cache first just in case (I use [this plugin](https://chrome.google.com/webstore/detail/clear-session/maejjihldgmkjlfmgpgoebepjchengka)). Thanks.

**Comment by cmontwill** [comment]
Ted, can we increase the weight of all the button labels 30-40% per what we discussed on slack?

**Comment by tedw** [comment]
This has been deployed
