### ISSUE TITLE
Hover and click state of tool tips are different

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#145]
If you hover over a glossary term, you see an unstyled tool tip. You have to click to see the styled version. Please update so that hover displays the styled version (I'm not sure if we also need a click-state. Maybe for mobile?)

Example seen here: https://live-aldf-wp.pantheonsite.io/article/foie-gras-legal-battle-continues-appellate-court-to-hear-arguments-over-local-eaterys-violations/

**Hover**

![screen shot 2018-06-20 at 12 36 20 pm](https://user-images.githubusercontent.com/13699106/41671938-97174b4e-7486-11e8-9684-a1e278eb8b44.png)

**Click**

![screen shot 2018-06-20 at 12 36 25 pm](https://user-images.githubusercontent.com/13699106/41671940-9abe8f3c-7486-11e8-9816-9c5726018560.png)

**Comment by tedw** [comment]
What you see when you hover and wait is the default browser tooltip for the `title` attribute text. We can remove this but we can’t style it. It was added as a no-JavaScript fallback.

**Comment by lizzycederberg** [comment]
Ahh gotcha. Is it very common that people won't have JS enabled? Seems like we should hide it, but I don't know how big of a deal that is.

**Comment by tedw** [comment]
This will take 15 min. Hiding when JS is enabled makes sense to me.

**Comment by lizzycederberg** [comment]
Let's hide these then please!

**Comment by tedw** [comment]
Ready for testing
