### ISSUE TITLE
"Hide Date" function does not work

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#146]
I tried hiding the date on this article, but it's still displaying on the front end: https://live-aldf-wp.pantheonsite.io/article/foie-gras-legal-battle-continues-appellate-court-to-hear-arguments-over-local-eaterys-violations/

Note: I changed it back on this article because this is real content. I was just testing it out.

**CMS**

![screen shot 2018-06-20 at 12 38 51 pm](https://user-images.githubusercontent.com/13699106/41672149-434e7e14-7487-11e8-8335-67e75722a6f8.png)

**Front end**

![screen shot 2018-06-20 at 12 39 01 pm](https://user-images.githubusercontent.com/13699106/41672150-435c2d2a-7487-11e8-895d-19bbd721c1f1.png)

**Comment by tedw** [comment]
This is probably due to caching.

**Comment by tedw** [comment]
Sorry, previous comment was meant for another ticket. Turns out this was never integrated.

**Comment by lizzycederberg** [comment]
I was able to successfully hide the date on this article: https://live-aldf-wp.pantheonsite.io/article/the-animal-legal-defense-fund-mourns-the-loss-of-tony-the-tiger/?message=pantheon-cleared-url-cache

But now when I try to revert it back to show the date, it's still hidden. I tried clearing the Pantheon cache and my browser cache just in case, but it's still not showing:

![screen shot 2018-06-22 at 3 11 19 pm](https://user-images.githubusercontent.com/13699106/41794786-8bd660f4-762e-11e8-8d24-d0347cf52a44.png)

**Comment by tedw** [comment]
Ready for testing

**Comment by lizzycederberg** [comment]
It's working! I tested hide and show, and both are working well.
