### ISSUE TITLE
"Hide in News" function does not work

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#148]
I tested this with this article because it's the first item in the results on News, but it still appears after updating the post: https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/

**CMS**

![screen shot 2018-06-20 at 12 53 20 pm](https://user-images.githubusercontent.com/13699106/41672871-10040662-7489-11e8-84b3-14fdaa1c03f9.png)

**News listing**

![screen shot 2018-06-20 at 12 53 25 pm](https://user-images.githubusercontent.com/13699106/41672872-1010d400-7489-11e8-828c-222042696541.png)

**Comment by tedw** [comment]
It’s probably because of caching.

**Comment by lizzycederberg** [comment]
@tedw Can you provide more info? Do you mean browser caching? Or server caching? 

I was making the updates in Chrome and reviewing them in FF because I haven't looked at the site in FF yet. 

If it's server-side caching, what is the best way to make a change live immediately?

**Comment by tedw** [comment]
Server. Is this urgent?

**Comment by lizzycederberg** [comment]
No, just trying to get everything into GH and trying to assess how major things are.

**Comment by lizzycederberg** [comment]
Note: Content is also appearing in the "related news" component when "Hide in News" is turned on, but it should not appear there either.

**Comment by lizzycederberg** [comment]
Working!
