### ISSUE TITLE
Jumpy image and button

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#151]
I don't know how to describe this issue, so I made a screen recording: https://drive.google.com/a/threespot.com/file/d/1aAS5x-_K072qqIwdpox5_N2WiPRtGXfv/view?usp=sharing

Here's the page: https://live-aldf-wp.pantheonsite.io/focus_area/farmed-animals/

I also noticed this on another page a while ago, so I don't think it's page-specific. 

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
That’s really weird. Can you try in an incognito window without the Pinterest plugin running? I have a feeling it’s related to that.

**Comment by lizzycederberg** [comment]
Ok so it still happens in incognito without the plugin, but it doesn't happen in FF or Safari. Maybe a Chrome issue?

**Comment by tedw** [comment]
Ok. This didn't happen for me. Let's have Lewis check it out.

**Comment by tedw** [comment]
@lizzycederberg Can you post your browser version number? I'm having a hard time reproducing this bug. I suspect it may be due to some other browser plugin. Could you install Chrome Canary and test again? https://www.google.com/chrome/browser/canary.html

**Comment by lizzycederberg** [comment]
@tedw It didn't happen in Canary

@lfrancis Can you please review this issue and see if you experience it in Chrome?

**Comment by lfrancis** [comment]
@lizzycederberg that looks like an interaction with a browser extension to allow you to save an image -- perhaps you have to restart the browser after disabling the extension in order fot the change to take? In any event, I can't replicate it.

**Comment by lizzycederberg** [comment]
Ok I haven't seen anyone else with this issue, so it must be one of my screen capture plugins or something. I'm going to leave it open as a `wontfix`

**Comment by tedw** [comment]
FWIW, it’s caused by this CSS `filter: drop-shadow(0 0 12px rgba(#000, 0.3));`
