### ISSUE TITLE
Action Alert too far left

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#153]
On pages where the action alert appears beneath a full-width component, it also gets pushed to the far left of the page. ALDF would like us to bring it back into the main content well area.

Example seen here: https://live-aldf-wp.pantheonsite.io/focus_area/farmed-animals/
Design: https://projects.invisionapp.com/share/FGG2CVFWZ8P#/screens

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Looks like a few things got messed up in this template when a did a big layout refactor the other week. Will address it.

**Comment by tedw** [comment]
Ready for testing

**Comment by lizzycederberg** [comment]
Looks good!
