### ISSUE TITLE
Large first letter missing on page

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#154]
This Issue page is not displaying the large first letter in the body copy: https://live-aldf-wp.pantheonsite.io/issue/wildlife-services-war-on-wildlife/

It's also missing on this issue: https://live-aldf-wp.pantheonsite.io/issue/ag-gag/

It's working fine on this other issue: https://live-aldf-wp.pantheonsite.io/issue/animals-in-entertainment/

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
There’s a typo in the template, `u-richtext--no-dropcap` should be `u-richtext--dropcap` 🤦‍♂️

**Comment by tedw** [comment]
Ready for testing

**Comment by lizzycederberg** [comment]
Looking good!
