### ISSUE TITLE
"read more" is not working

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#156]
ALDF inserted the "read more" function in this post: https://live-aldf-wp.pantheonsite.io/article/animal-neglect-facts/

I see it in the CMS, but it doesn't appear on the page

**CMS**

![screen shot 2018-06-22 at 12 46 52 pm](https://user-images.githubusercontent.com/13699106/41788757-b6f98522-761a-11e8-9127-97c98e6bd9d0.png)

**Page**

![screen shot 2018-06-22 at 12 47 14 pm](https://user-images.githubusercontent.com/13699106/41788749-b19d75ac-761a-11e8-9136-6ab839e79704.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
I think the original specs said this would only be implemented on Issue pages. What pages to we need this on?

**Comment by lizzycederberg** [comment]
Ahhh I see. I think we need it on all pages now 😬

**Comment by tedw** [comment]
That’s annoying, but should not take more than 1 hr.

**Comment by tedw** [comment]
@lizzycederberg FYI all those `<span style="font-weight: 400;">` tags are breaking this functionality. I’m going to try to fix it but am not going to spend very long on it.

**Comment by tedw** [comment]
I was able to fix it fairly easily, deploying now.

**Comment by lizzycederberg** [comment]
Working well!
