### ISSUE TITLE
Right Rail Link styling

### ISSUE THREAD

**Issue by cmontwill** [Threespot/aldf-wp#158]
Right rail nav top item should not have an arrow and be uppercase.

Current:
https://live-aldf-wp.pantheonsite.io/about-us/

Desired:
https://projects.invisionapp.com/share/9EG2CZT2H37#/screens

**Comment by tedw** [comment]
@cmontwill This changed. See #57

**Comment by lizzycederberg** [comment]
@cmontwill Can you look at this please?

**Comment by cmontwill** [comment]
Ahhh...sorry this came in from EP and now I see what she wants. She just wanted the upper case back with a little more padding between the links. Something like this....

![screen shot 2018-06-26 at 5 21 22 pm](https://user-images.githubusercontent.com/5890745/41940054-7f41f580-7965-11e8-99f2-4cb81a2ffeb9.png)

**Comment by tedw** [comment]
Updated, heading is uppercase now

**Comment by cmontwill** [comment]
@lizzycederberg good here.
