### ISSUE TITLE
Search filters may not be working with keyword search

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#159]
I was trying to find all the cases related to "Tony the Tiger" and I knew that they were also all under the "Captive Animals" taxonomy, so I applied the "Captive Animals" filter in search but didn't see them: https://live-aldf-wp.pantheonsite.io/?s=&taxonomy_focus_area=captive-animals&taxonomy_how_we_work=&date_range=&post_type= 

![screen shot 2018-06-22 at 2 54 54 pm](https://user-images.githubusercontent.com/13699106/41794144-62de078a-762c-11e8-8499-4cae4c681ffb.png)

I then added "tony the tiger" in the search bar and got 0 results: https://live-aldf-wp.pantheonsite.io/?s=tony+the+tiger&taxonomy_focus_area=captive-animals&taxonomy_how_we_work=&date_range=&post_type=

![screen shot 2018-06-22 at 2 53 02 pm](https://user-images.githubusercontent.com/13699106/41794148-668caaee-762c-11e8-9868-3c2ddb5e1d6a.png)

I hit 'clear all' to remove the "Captive Animals" filter and all the content showed up: https://live-aldf-wp.pantheonsite.io/search/tony+the+tiger/

![screen shot 2018-06-22 at 2 55 30 pm](https://user-images.githubusercontent.com/13699106/41794133-5c4aa414-762c-11e8-9be5-71e7f9f82307.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by lizzycederberg** [comment]
When I apply Content Type > Issue filter, I get results for News items

![screen shot 2018-06-29 at 3 07 55 pm](https://user-images.githubusercontent.com/13699106/42110170-39c1145a-7bae-11e8-8f5c-bcc482116fcf.png)

**Comment by tedw** [comment]
It is also strange that these 2 URLs provide different results:

http://live-aldf-wp.pantheonsite.io/search/laws+protect+animals/

http://live-aldf-wp.pantheonsite.io/?s=laws+protect+animals&taxonomy_focus_area=&taxonomy_how_we_work=&date_range=&post_type=

**Comment by lizzycederberg** [comment]
Working
