### ISSUE TITLE
Text promo is left aligned

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#160]
On this page, there's a Text Promo towards the bottom of the page that is left-aligned instead of centered: https://live-aldf-wp.pantheonsite.io/article/animal-fighting-facts/

![screen shot 2018-06-25 at 11 10 56 am](https://user-images.githubusercontent.com/13699106/41858669-73117ffe-7868-11e8-8f40-2e1619f85613.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
It technically is centered and full width, since this page has a right sidebar. The text promo component was not meant to be used by itself after the body copy, it was meant to break up the body copy.

**Comment by lizzycederberg** [comment]
Elizabeth approved not changing this
