### ISSUE TITLE
Related Cases illustration + focus area to be a consistent height

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#163]
@cmontwill Can you please provide guidance on this:

When we show related Cases, ALDF would like the illustration + focus area header to be the same height across items, but some are 1 line and some are 2 lines

Example page: https://live-aldf-wp.pantheonsite.io/issue/wildlife-services-war-on-wildlife/

![screen shot 2018-06-25 at 12 23 13 pm](https://user-images.githubusercontent.com/13699106/41862785-dd77cec0-7872-11e8-9934-aee008536545.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by cmontwill** [comment]
@tedw 
Can we reduce the desktop size of the focus area from from 1.25 to 1em and the case label from 1.125 to 1em? I think that puts them at 14px. See below...
![screen shot 2018-06-25 at 1 11 01 pm](https://user-images.githubusercontent.com/5890745/41864839-4107f5ae-7879-11e8-9694-1a2fef3b3131.png)

**Comment by tedw** [comment]
Updated.

Since there are often only 1 or 2 items, I updated the styles to make it 2-col by default, switching to 3-col only when there are 3 items.

I also set a max-width in "tablet" view to prevent the lines from getting too long.

**Comment by cmontwill** [comment]
@lizzycederberg looks good here.

**Comment by lizzycederberg** [comment]
Ok closing!
