### ISSUE TITLE
Sticky nav is hiding anchor links

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#165]
When on a large screen and the sticky nav is in place, if you click a jump link the anchor H2 is covered up by the nav

Example here: https://live-aldf-wp.pantheonsite.io/project/florida-orca-protection-act/#contact-your-representative

Clicked "Get Involved" but you can't see it

![screen shot 2018-06-26 at 11 55 33 am](https://user-images.githubusercontent.com/13699106/41924386-e2e34f54-7937-11e8-8602-65b4c9c31119.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Ugh, this is what happens when we introduce new functionality at the last minute after QA is complete.

I will address this.

**Comment by tedw** [comment]
FYI, the content on this page is a huge mess, looks like they copied from Word or something. I just cleaned it up but we may need to remind them of authoring best practices.

**Comment by tedw** [comment]
I addressed this using CSS only, which is the fastest and most accessible solution. The downside is that it adds space above the target heading, so when you scroll up you will see extra space.

The only way to avoid this is to use JS to adjust the scroll position but this will take 1–2 hrs to implement.

**Comment by lizzycederberg** [comment]
I think this is ok. Reporting resolved to the client.
