### ISSUE TITLE
Image gallery display issue

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#166]
When Elizabeth clicks on an image in a gallery, she gets this weird chopped view and it "freezes" the page -- meaning she has to click out of it to get back to the page: https://live-aldf-wp.pantheonsite.io/focus_area/captive-animals/

![image002](https://user-images.githubusercontent.com/13699106/41927931-a108bc54-7941-11e8-8b5d-0a9151772cd0.jpg)

She's using Chrome, which is also what I'm using but I see this:

![screen shot 2018-06-26 at 11 59 20 am](https://user-images.githubusercontent.com/13699106/41927963-b7fa9a0e-7941-11e8-86f9-c2432bbaf80a.png)

**Elizabeth said we can disable clicking on images if that's a simple solution.** 
 
  
  
  

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
I fixed this earlier today

**Comment by lizzycederberg** [comment]
Working well!
