### ISSUE TITLE
Remove Focus Area, display Content Type in search results

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#167]
@tedw Elizabeth wants to show the **content type** on search results in place of the Focus Area. 

In the case of Articles, she's like to see the **specific article type**. 

Is this doable?

![screen shot 2018-06-26 at 1 08 29 pm](https://user-images.githubusercontent.com/13699106/41928078-0a12bd1c-7942-11e8-8f29-f2ef3f6a2b19.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by lizzycederberg** [comment]
Will show the content type name for all content types, except Pages which will show nothing. 

If an article has an article type, the article type will show. If the article does not have an article type, Article will show.

**Comment by tedw** [comment]
Deployed http://live-aldf-wp.pantheonsite.io/search/orca/

**Comment by lizzycederberg** [comment]
Looks great!

**Comment by tedw** [comment]
This requires each content type have a listing view, which we currently don’t have for “How We Work” or “Projects.”

**Comment by lizzycederberg** [comment]
We do not need to add filters or facets for them, but they do need listing styles. Can they be modeled off the Article listing?

**Comment by tedw** [comment]
Created a new issue https://github.com/Threespot/aldf-wp/issues/177
