### ISSUE TITLE
Google map integration

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#168]
The map seen here http://aldf.org/about-us/saldf/student-animal-legal-defense-fund-chapters/ needs to be added to this page: https://live-aldf-wp.pantheonsite.io/article/animal-protection-laws-of-the-united-states-of-america/

Please let me know if you need anything from ALDF for this. 

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by lizzycederberg** [comment]
@tedw I just re-read David's note on this and he said "we need to discuss the migration plan" so I think he can help with this but needs some guidance.

**Comment by tedw** [comment]
This is not a simple iframe. There is a lot of custom code here, both JS and PHP. I can copy the map code over but the rest of the functionality (search, chapter listing, pagination) is not possible since we don't have Chapters on the new site.

Just copying the map will take ~2 hrs. Adding Chapters as content types and building the rest of the functionality will take at least 8 hrs.

**Comment by lizzycederberg** [comment]
Ok let me email David and ask him about this

**Comment by lizzycederberg** [comment]
@tedw David is ok with losing search and the content types, but asked is we can add the schools URLs to the results. What do you need to do this? Or can you do it with the content as is?

**Comment by tedw** [comment]
Map has been migrated

**Comment by tedw** [comment]
Oh, right, I forgot about that. Perhaps for now I could use Google’s “felling luck” URL to go to the first result using the law school’s name.

e.g. http://www.google.com/webhp?#q=georgetown+law+school&btnI=I

**Comment by tedw** [comment]
I just added links using the Google solution above. Seems to work fine.
