### ISSUE TITLE
Advocacy missing from How We Work menu

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#171]
I can't remember how to add items here or I would do it myself...

The Advocacy page should appear under How We Work: https://live-aldf-wp.pantheonsite.io/how_we_work/advocacy/

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Not sure why that was happening but I made an update to sort them alphabetically and that seems to have fixed it ¯\_(ツ)_/¯

**Comment by lizzycederberg** [comment]
Looks like we might be running into a space issue actually. Collaboration is now missing from the list.

**Comment by tedw** [comment]
Fixed, WP limits the number of posts returned to 5 by default for some reason. I set it to show all. Deploying.

**Comment by lizzycederberg** [comment]
@tedw I'm still only seeing 5 items and not Collaboration

**Comment by tedw** [comment]
It has not been deployed yet. I wait to assign tickets back to you until they are ready for testing.

**Comment by tedw** [comment]
Deployed

**Comment by lizzycederberg** [comment]
💯
