### ISSUE TITLE
View: Key Dates | Full Timeline toggle is missing

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#173]
The toggle to allow users to view key dates only or the full timeline is missing from pages and only key dates are showing up. 

Example seen here: https://live-aldf-wp.pantheonsite.io/issue/ag-gag/

**CMS**

![screen shot 2018-06-27 at 6 04 36 pm](https://user-images.githubusercontent.com/13699106/42002253-944e8360-7a34-11e8-9e06-efe6f9688a28.png)

**Front end -- missing toggle and June 22nd**

![screen shot 2018-06-27 at 6 04 01 pm](https://user-images.githubusercontent.com/13699106/42002230-7f48121a-7a34-11e8-81b8-ae7b72f4f1c7.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
I updated it to hide the toggle when there is nothing to show (i.e. No hidden dates).

**Comment by lizzycederberg** [comment]
This post does have hidden dates, though. The first one (June 22) is supposed to be hidden.

**Comment by tedw** [comment]
I think this is actually due to a JS error with the image gallery. Not sure what happened to it but looking into it.

**Comment by tedw** [comment]
Actually, there was also a bug with the timeline JS. Fixed now and deploying.

**Comment by tedw** [comment]
Deployed

**Comment by lizzycederberg** [comment]
🙌 looking good!
