### ISSUE TITLE
One more map

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#179]
The map seen here http://aldf.org/animal-law-courses/ needs to go on this page: https://live-aldf-wp.pantheonsite.io/article/animal-law-courses/

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Done https://live-aldf-wp.pantheonsite.io/article/animal-law-courses/

**Comment by lizzycederberg** [comment]
🙌  awesome
