### ISSUE TITLE
"article" filter is returning 0 results in search

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#180]
The articles filter is returning 0 results -- maybe because they have subtypes?

https://live-aldf-wp.pantheonsite.io/?s=tiger&taxonomy_focus_area=&taxonomy_how_we_work=&date_range=&post_type=article

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
This seems to be fixed by adding `_type` (e.g. `post_type=article` should be `post_type=article_type`)

**Comment by lizzycederberg** [comment]
Working!
