### ISSUE TITLE
Remove limit on the number of people that can be added to the People List component

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#182]
@tedw They need to be able to add more than 9 people to a list. 

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Deployed

**Comment by lizzycederberg** [comment]
Testing and seems to be working well. Thanks!
