### ISSUE TITLE
Update helper text in search boxes

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#183]
ALDF wants some indicator to help users know they can search for exact matches by using quotes. @cmontwill Please provide direction on the solution for this:

![screen shot 2018-07-02 at 4 29 46 pm](https://user-images.githubusercontent.com/13699106/42184978-45385e56-7e15-11e8-84b2-b0eb4868db52.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by cmontwill** [comment]
@tedw First of all, I'm sorry you have to do this. But here it is:

![screen shot 2018-07-03 at 5 38 34 pm](https://user-images.githubusercontent.com/5890745/42245767-03c4fa6e-7ee8-11e8-9414-548ec287d2d2.png)

**Comment by tedw** [comment]
What if we figure out how to weight the title higher than other fields?

**Comment by lizzycederberg** [comment]
@tedw I like that language better 👍

**Comment by tedw** [comment]
Updated

**Comment by lizzycederberg** [comment]
Like it!

**Comment by lizzycederberg** [comment]
Gone!
