### ISSUE TITLE
Exclude content from appearing in recent news if you're already on the page

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#184]
On this page: https://live-aldf-wp.pantheonsite.io/article/the-legal-process-in-the-united-states-a-criminal-case/

In 'recent news' the article is shown at the top. Can we create a rule to hide content from the listing when you're already on that page?

![screen shot 2018-07-02 at 4 32 15 pm](https://user-images.githubusercontent.com/13699106/42185064-a17caf14-7e15-11e8-83b7-52f5f9d5f9c9.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by lizzycederberg** [comment]
I'm bumping this up to Thursday's list because it seems related to #148

**Comment by tedw** [comment]
Looks fine now, and we should already be filtering out the current page, so perhaps they had manually chosen the same page in the related new component?

**Comment by lizzycederberg** [comment]
Will keep an eye out, but closing for now.
