### ISSUE TITLE
Allow admins to pull in any page, any content type in the Related Content component

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#187]
Please remove any restrictions on selectable content types in the `2-up Related Content component` in the `Related Content` section (already done in `Resources`). Elizabeth is trying to add an Issue and they are not currently included there. 

![screen shot 2018-07-05 at 2 45 48 pm](https://user-images.githubusercontent.com/13699106/42341751-23196622-8062-11e8-8d50-be975d5981df.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by lizzycederberg** [comment]
@tedw Something must have gone wrong. Now I'm not able to find that Issue page in either Resources or Related Content

![screen shot 2018-07-05 at 3 59 24 pm](https://user-images.githubusercontent.com/13699106/42345178-8797f8b6-806c-11e8-98b4-1cf049661d25.png)

**Comment by tedw** [comment]
I found it without the quotes around the search term, must be a search issue.

If you use the taxonomy filter it shows up as the first Issue.

![aldf-related](https://user-images.githubusercontent.com/864716/42347348-aa6f43d8-8073-11e8-98dc-0dc28e449ef6.gif)

**Comment by lizzycederberg** [comment]
Did you change search in the CMS at all? The exact phrase search with quotes was working well last week.

**Comment by tedw** [comment]
Solr is currently disabled in the admin for ACF components. Should I re-enable it?

**Comment by tedw** [comment]
Deployed, results are much better now. Searching `animals entertainment` without quotes has that Issue page showing up as the 6th result (the previous 5 are Articles).

**Comment by lizzycederberg** [comment]
Working well now! Thanks!
