### ISSUE TITLE
Custom post type URLs use underscores instead of dashes

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#191]
This is breaking dynamically-generated links, like the “How We Work” links in the footer.

E.g. current format: `https://live-aldf-wp.pantheonsite.io/how-we-work/legal-education/`
E.g. desired format: `https://live-aldf-wp.pantheonsite.io/how_we_work/legal-education/`

**Comment by tedw** [comment]
These are dynamically generated. The real issue is that I haven’t been able to figure out how to get WP to use dashes instead of underscores without breaking other functionality.

**Comment by tedw** [comment]
I don’t think we can change the underscores to dashes so I just updated the URLs to use underscores.

**Comment by lizzycederberg** [comment]
Works for me!
