### ISSUE TITLE
Review redirect formatting 

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#192]
@tedw Can you please review how David's entered redirects and make sure they are accurate. Looks like he's using full URLS instead of relative, which I think it wrong.

https://live-aldf-wp.pantheonsite.io/wp/wp-admin/tools.php?page=redirection.php

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Correct, he should **NOT** be using full URLs.

**Comment by tedw** [comment]
These look fine

**Comment by lizzycederberg** [comment]
Thanks!
