### ISSUE TITLE
Facts and actions are appearing in search results

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#193]
These should not appear in search results. They do not really have pages.

**Fact** -- directs the user to the homepage
searched "foie gras"
![screen shot 2018-07-10 at 10 16 29 am](https://user-images.githubusercontent.com/13699106/42515726-712065d4-842a-11e8-927b-23a840b43ea8.png)

**Action**
searched "kristen lindsey"
![screen shot 2018-07-10 at 10 15 47 am](https://user-images.githubusercontent.com/13699106/42515723-6e4b20c4-842a-11e8-8b39-356f73608e43.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
@matbrady Did you have to set these post types to be included in search to make the Related News components work? I just reset them to be excluded for now.

@lizzycederberg I just triggered a reindex. You may need to manually clear the cache once that's done.

**Comment by tedw** [comment]
Hmm, maybe the re-index was cancelled when I closed my tab. I thought it would continue in the background but maybe not. Running again.

**Comment by tedw** [comment]
Didn’t seem to work 😑

**Comment by tedw** [comment]
It's weird because Facts and Actions aren’t included in the list of indexed content types:
https://live-aldf-wp.pantheonsite.io/wp/wp-admin/admin.php?page=solr-power#top#solr_info

```
Indexing Stats by Post Type
post: 0
page: 28
attachment: 0
article: 779
case: 22
focus_area: 5
issue: 8
project: 10
external_link: 5
document: 78
person: 71
how_we_work: 7
```

**Comment by lizzycederberg** [comment]
Not anymore!
