### ISSUE TITLE
Tags have disappeared from the frontend

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#194]
The manually added tags used to appear below the Focus Area and How We Work section, but now it's blank: 

e.g. https://live-aldf-wp.pantheonsite.io/article/animal-legal-defense-fund-urges-usda-inspection-for-tony-the-tiger/

**CMS**
![screen shot 2018-07-10 at 10 20 38 am](https://user-images.githubusercontent.com/13699106/42516045-2f9cf694-842b-11e8-9ba9-ff295e13691a.png)

**Frontend**
![screen shot 2018-07-10 at 10 22 52 am](https://user-images.githubusercontent.com/13699106/42516064-3a354908-842b-11e8-884c-475499e16235.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
They show up again once you click "Update" in the admin. This has to do with an update we made after content had been migrated. Have not been able to figure out an automated fix yet.

**Comment by lizzycederberg** [comment]
Ooooh yeah. Ok well that's ok I will start updating pages and if they report specific cases I know how to fix them. I think we knew about this and I forgot. Thanks!

**Comment by lizzycederberg** [comment]
Chris and I manually updated all the content!
