### ISSUE TITLE
When there is no excerpt on a piece of content, show the first few lines from the body

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#195]
This would apply to:
- Articles
- Projects
- Cases
- Issues
- How We Work
- Focus Areas
- Pages
- People

**Examples**:

https://live-aldf-wp.pantheonsite.io/article/how-undergraduate-students-can-get-involved-in-animal-law/
![screen shot 2018-07-11 at 10 33 15 am](https://user-images.githubusercontent.com/13699106/42579416-48c7b660-84f6-11e8-837c-f4e6cc4e9e8f.png)

https://live-aldf-wp.pantheonsite.io/focus_area/captive-animals/
![screen shot 2018-07-11 at 10 35 15 am](https://user-images.githubusercontent.com/13699106/42579445-576dc65a-84f6-11e8-8225-4fd899459976.png)

https://live-aldf-wp.pantheonsite.io/article/candy-chimps-case-fight-captive-animals-goes/
![screen shot 2018-07-11 at 10 35 11 am](https://user-images.githubusercontent.com/13699106/42579452-5ad7ec12-84f6-11e8-8607-8b9a035bc0dd.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
I swear we already implemented this. Will look into it.

**Comment by tedw** [comment]
Fixed

- http://live-aldf-wp.pantheonsite.io/search/how+undergraduate+students/
- http://live-aldf-wp.pantheonsite.io/?s=captive+animals
- http://live-aldf-wp.pantheonsite.io/search/candy+chimp+case/

**Comment by lizzycederberg** [comment]
💯 great!
