### ISSUE TITLE
The first letter in the pull quote on the homepage is not displaying

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#197]
The quote in the CMS is "I think the public has made the decision that going and seeing the performance of orcas, that day has come and gone."

![screen shot 2018-07-12 at 10 29 58 am](https://user-images.githubusercontent.com/13699106/42639665-9136cbb6-85be-11e8-8a93-89ac680e9f14.png)

**The quote on the homepage is missing the "I" at the beginning**

![screen shot 2018-07-12 at 10 30 05 am](https://user-images.githubusercontent.com/13699106/42639667-93cd6790-85be-11e8-8993-fa967422cdf2.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Fixed, and I removed the extra “I“ Elizabeth added as a temporary fix.
