### ISSUE TITLE
Hide the date on 2-Up Related Content Component

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#198]
So we don't have to change the logic of the "hide date" toggle again, we are going to **remove all dates** from the front end of the "Resources" and "Related Content" in the `2-up related content` component

e.g. https://live-aldf-wp.pantheonsite.io/issue/ag-gag/

![screen shot 2018-07-12 at 11 14 00 am](https://user-images.githubusercontent.com/13699106/42642364-b6a6286e-85c4-11e8-99ab-fe82d83da8aa.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by lizott** [comment]
@tedw what is the status on this ticket? it needs to be closed out today.

**Comment by tedw** [comment]
Dates have been removed
