### ISSUE TITLE
Search result thumbs MIA

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#205]
http://dev-aldf-wp.pantheonsite.io/search/native?s=native

Search result thumbnails are MIA.

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Please test on the live environment. No images show up on dev.

http://live-aldf-wp.pantheonsite.io

**Comment by lfrancis** [comment]
Confirmed fine on live
