### ISSUE TITLE
Legal Resources Disappearing

### ISSUE THREAD

**Issue by cmontwill** [Threespot/aldf-wp#206]
@tedw 

A little issue with legal resources just bubbled up. It seems when a resource has content in it
its not showing up in the search: 
https://live-aldf-wp.pantheonsite.io/articles/?article_type=legal-resource

Here's a resource without content:
https://live-aldf-wp.pantheonsite.io/article/rodeo-facts-the-case-against-rodeos/

and a resource with content: 
https://live-aldf-wp.pantheonsite.io/article/animal-cruelty-and-domestic-violence/

I checked and the taxonomy seems to be applied correctly. 

Resources are still in the back end....
https://live-aldf-wp.pantheonsite.io/wp/wp-admin/edit.php?s&post_status=all&post_type=article&action=-1&m=0&article_type=legal-resource&focus_area_type&seo_filter&readability_filter&filter_action=Filter&paged=1&action2=-1

We should have ~60 resources in there FWIW.

Also, and I dont know if this matters, but we're getting some php errors in the dashboard. 

![screen shot 2018-07-13 at 11 48 30 am](https://user-images.githubusercontent.com/5890745/42700791-c9355bca-8692-11e8-9202-8b23c87242e9.png)

Thoughts? 

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by matbrady** [comment]
> PROPOSED SOLUTION
The logic should be updated so that it only applies to this view of the articles listings page /articles/?article_type=news -- but if this logic is applied items will appear in the full articles listing.
@cmontwill totally doable! 👍

**Comment by tedw** [comment]
This has been deployed
