### ISSUE TITLE
Search icon issues on mobile

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#207]
http://dev-aldf-wp.pantheonsite.io/?s=cat

Shown is iPhone 7 running latest iOS:

![img_b532cfbd34f0-1](https://user-images.githubusercontent.com/6942589/42699599-3b96ce1e-868f-11e8-87dc-b4909271c300.jpeg)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by lizott** [comment]
@tedw please prioritize the Friday tasks before reviewing these tickets.

**Comment by tedw** [comment]
I am prioritizing Friday tasks.

**Comment by lizott** [comment]
THANK YOU. 🙏

**Comment by tedw** [comment]
Fix has been deployed

**Comment by lfrancis** [comment]
Confirmed addressed
