### ISSUE TITLE
This link is broken. The link target could not be loaded due to an HTTP error.

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#209]
This link is broken. The link target could not be loaded due to an HTTP error.
Broken Link
4 pages

This is sometimes a temporary problem, but if it persists it indicates a serious problem on your web server.

Broken link: ‘Bizarro’ http://www.bizarro.com/vegan/index.htm 503 Server Unavailable
http://dev-aldf-wp.pantheonsite.io/about-us/about-us-testimonials/
Line 488

Broken link: The Tiger Next Door http://www.thetigernextdoor.com/ 500 Internal Server Error
http://dev-aldf-wp.pantheonsite.io/article/film-screening-suggestions/
Line 500

Broken link: The Tiger Next Door http://www.thetigernextdoor.com/ 500 Internal Server Error
http://dev-aldf-wp.pantheonsite.io/article/student-animal-legal-defense-fund-saldf-program-guides/2016-2018-student-animal-legal-defense-fund-program-guide-captive-wild-animals/
Line 499

Broken link: Rooterville http://www.rooterville.org/ 503 Server Unavailable
http://dev-aldf-wp.pantheonsite.io/article/university-of-florida-volunteering-at-rooterville/
Line 448

Broken link: The Regal Vegan http://www.theregalvegan.com/site/ 500 Internal Server Error
http://dev-aldf-wp.pantheonsite.io/issue/foie-gras/
Line 459

Broken link: The Regal Vegan http://www.theregalvegan.com/site/ 500 Internal Server Error
http://dev-aldf-wp.pantheonsite.io/issue/foie-gras/380/
Line 459

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Moved broken link issues to #216
