### ISSUE TITLE
This link is broken. The name of the target web server not found in DNS.

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#210]
This link is broken. The name of the target web server not found in DNS.
Broken Link
10 pages

This often occurs when the destination site is no longer operating, or www. has been omitted from the front of the domain name. It can also be a transient issue if the local DNS cache server is temporarily unavailable.

Broken link: Animal Welfare Act (AWA), 7 USC §2131 – §2159 http://awic.nal.usda.gov/nal_display/index.php?info_center=3&tax_level=3&tax_subject=182&topic_id=1118&level3_id=6735&level4_id=0
http://dev-aldf-wp.pantheonsite.io/article/animal-neglect-facts/animal-neglect-facts-federal-law/
Line 439

Broken link: Kentucky Bar Association Animal Law Section https://www.kybar.org/page/animallaw
http://dev-aldf-wp.pantheonsite.io/article/bar-association-animal-law-sections-and-committees/
Line 483

Broken link: Kentucky State Bar Equine Section https://www.kybar.org/page/Equine
http://dev-aldf-wp.pantheonsite.io/article/bar-association-animal-law-sections-and-committees/
Line 488

Broken link: State Bar of Michigan Animal Law Section http://connect.michbar.org/animallaw/home/
http://dev-aldf-wp.pantheonsite.io/article/bar-association-animal-law-sections-and-committees/
Line 502

Broken link: State Bar of Nevada Animal Law Section https://www.nvbar.org/member-services-3895/sections/animal-law-section/
http://dev-aldf-wp.pantheonsite.io/article/bar-association-animal-law-sections-and-committees/
Line 513

Broken link: Back to Nature Wildlife Refuge http://www.btn-wildlife.org/
http://dev-aldf-wp.pantheonsite.io/article/barry-university-school-of-law-stepping-up-to-protect-animals/
Line 445

Broken link: One Tail at a Time http://www.onetailatatime.org/
http://dev-aldf-wp.pantheonsite.io/article/chicago-kent-college-of-law-foie-gras-panel/
Line 449

Broken link: http://dev-aldf-wp.pantheonsite.iohttp//dev-aldf-wp.pantheonsite.io/wp-content/uploads/staff/headshot/tom-linney.jpg
http://dev-aldf-wp.pantheonsite.io/article/where-are-they-now-tom-linney/
Line 443

Broken link: describes Kittles history http://communities.justicetalking.org/blogs/day17/archive/2007/06/13/no-it-s-just-a-dog-animal-abuse-and-beyond.aspx
http://dev-aldf-wp.pantheonsite.io/case/animal-hoarding-case-study-vikki-kittles/
Line 513

Broken link: Despite legal requirements http://awic.nal.usda.gov/alternatives/3rs
http://dev-aldf-wp.pantheonsite.io/focus-area/animals-used-in-research/
Line 482

Broken link: Despite legal requirements http://awic.nal.usda.gov/alternatives/3rs
http://dev-aldf-wp.pantheonsite.io/focus_area/animals-used-in-research/
Line 482

Broken link: Despite legal requirements http://awic.nal.usda.gov/alternatives/3rs
http://dev-aldf-wp.pantheonsite.io/focus_area/animals-used-in-research/380/
Line 482

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Moved broken link issues to #216
