### ISSUE TITLE
This link may be broken. The target page has taken a long time to load and timed out.

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#213]
This link may be broken. The target page has taken a long time to load and timed out.
Broken Link
6 pages

This is often a temporary problem, but if the problem persists it indicates network problems or an issue on your web server.

Broken link: Globalization and Animal Law http://www.kluwerlaw.com/Catalogue/titleinfo.htm?ProdID=9041133380
http://dev-aldf-wp.pantheonsite.io/article/animal-law-books-periodicals/
Line 495

Broken link: Amy Chaitoff http://aldf-old.live2.radicaldesigns.org/system/amy@chaitofflaw.com
http://dev-aldf-wp.pantheonsite.io/article/bar-association-animal-law-sections-and-committees/
Line 579

Broken link: 2008 “One Earth: Globalism and Animal Law” conference at Lewis and Clark Law School http://legacy.lclark.edu/org/saldf/conference.html
http://dev-aldf-wp.pantheonsite.io/article/chapman-university-school-of-law-raising-funds-and-awareness-for-animals/
Line 442

Broken link: American Bar Association http://www.abanet.org/legalservices/findlegalhelp/home.cfm
http://dev-aldf-wp.pantheonsite.io/article/how-to-find-an-attorney-to-help-you-with-your-animal-related-issues/
Line 444

Broken link: www.abanet.org http://www.abanet.org/
http://dev-aldf-wp.pantheonsite.io/article/how-to-find-an-attorney-to-help-you-with-your-animal-related-issues/
Line 451

Broken link: Oxfam America http://www.oxfamamerica.org/static/media/files/Oxfam_Poultry_Workers_Brief_October_26_5UhpYvF.pdf
http://dev-aldf-wp.pantheonsite.io/article/tyson-repeat-osha-violator-gives-its-workers-lip-service-instead-of-safer-conditions/
Line 444

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Moving all broken link issues to #216
