### ISSUE TITLE
This link returns a 403 HTTP status code.

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#214]
This link returns a 403 HTTP status code.
Broken Link
3 pages

Web servers return this code when access is denied to a URL.

Link: Animal Law Conference at Lewis and Clark Law School http://law.lclark.edu/centers/animal_law_studies/events/animal_law_conference/ 403 Forbidden
http://dev-aldf-wp.pantheonsite.io/article/meet-aldf-ll-m-scholar-aurora-paulsen/
Line 443

Link: Animal Law Conference at Lewis and Clark Law School http://law.lclark.edu/centers/animal_law_studies/events/animal_law_conference/ 403 Forbidden
http://dev-aldf-wp.pantheonsite.io/article/where-are-they-now-alexis-fox/
Line 446

Link: Humane Education Advocates Reaching Teachers https://teachheart.org/heart/ 403 Forbidden
http://dev-aldf-wp.pantheonsite.io/article/where-are-they-now-chris-parucci/
Line 443

Link: Animal Law Conference at Lewis and Clark Law School http://law.lclark.edu/centers/animal_law_studies/events/animal_law_conference/ 403 Forbidden
http://dev-aldf-wp.pantheonsite.io/article/where-are-they-now-emily-davidsohn/
Line 449

Link: Animal Law Conference at Lewis and Clark Law School http://law.lclark.edu/centers/animal_law_studies/events/animal_law_conference/ 403 Forbidden
http://dev-aldf-wp.pantheonsite.io/article/where-are-they-now-natalie-prosin/
Line 445

Link: Va. Code Ann. § 3.2-6504.1 http://law.lis.virginia.gov/vacode/title3.2/chapter65/section3.2-6504.1/ 403 Forbidden
http://dev-aldf-wp.pantheonsite.io/project/an-avoidable-tragedy-dogs-in-hot-cars/
Line 522

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Moving all broken link issues to #216
