### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by tedw** [Threespot/aldf-wp#216]
# External Links

**Globalization and Animal Law**
http://www.kluwerlaw.com/Catalogue/titleinfo.htm?ProdID=9041133380

- https://live-aldf-wp.pantheonsite.io/article/animal-law-books-periodicals/

**Amy Chaitoff**
http://aldf-old.live2.radicaldesigns.org/system/amy@chaitofflaw.com

- https://live-aldf-wp.pantheonsite.io/article/bar-association-animal-law-sections-and-committees/

**2008 “One Earth: Globalism and Animal Law” conference at Lewis and Clark Law School**
http://legacy.lclark.edu/org/saldf/conference.html

- https://live-aldf-wp.pantheonsite.io/article/chapman-university-school-of-law-raising-funds-and-awareness-for-animals/

**American Bar Association** 
http://www.abanet.org
**New URL:** https://www.americanbar.org

- https://live-aldf-wp.pantheonsite.io/article/how-to-find-an-attorney-to-help-you-with-your-animal-related-issues/

**American Bar Association - Find Legal Help**
http://www.abanet.org/legalservices/findlegalhelp/home.cfm
**New URL:** https://www.americanbar.org/groups/legal_services/flh-home.html)

- https://live-aldf-wp.pantheonsite.io/article/how-to-find-an-attorney-to-help-you-with-your-animal-related-issues/

**Oxfam America**
http://www.oxfamamerica.org/static/media/files/Oxfam_Poultry_Workers_Brief_October_26_5UhpYvF.pdf

- https://live-aldf-wp.pantheonsite.io/article/tyson-repeat-osha-violator-gives-its-workers-lip-service-instead-of-safer-conditions/

**Independent Charities Seal of Excellence**
http://www.independentcharities.org/find/charitypage.php?id=1&ein=94-2681680&key=

- http://dev-aldf-wp.pantheonsite.io/about-us/financials/

**‘Bizarro’**
http://www.bizarro.com/vegan/index.htm
- https://live-aldf-wp.pantheonsite.io/about-us/about-us-testimonials/

**The Tiger Next Door**
http://www.thetigernextdoor.com/
- https://live-aldf-wp.pantheonsite.io/article/film-screening-suggestions/
- https://live-aldf-wp.pantheonsite.io/article/student-animal-legal-defense-fund-saldf-program-guides/2016-2018-student-animal-legal-defense-fund-program-guide-captive-wild-animals/

**Rooterville**
http://www.rooterville.org/
- https://live-aldf-wp.pantheonsite.io/article/university-of-florida-volunteering-at-rooterville/

**The Regal Vegan**
http://www.theregalvegan.com/site/
- https://live-aldf-wp.pantheonsite.io/issue/foie-gras/
- https://live-aldf-wp.pantheonsite.io/issue/foie-gras/380/

**Animal Welfare Act (AWA), 7 USC §2131 – §2159**
http://awic.nal.usda.gov/nal_display/index.php?info_center=3&tax_level=3&tax_subject=182&topic_id=1118&level3_id=6735&level4_id=0
- https://live-aldf-wp.pantheonsite.io/article/animal-neglect-facts/animal-neglect-facts-federal-law/

**Kentucky Bar Association Animal Law Section**
https://www.kybar.org/page/animallaw
- https://live-aldf-wp.pantheonsite.io/article/bar-association-animal-law-sections-and-committees/

**Kentucky State Bar Equine Section**
https://www.kybar.org/page/Equine
- https://live-aldf-wp.pantheonsite.io/article/bar-association-animal-law-sections-and-committees/

**State Bar of Michigan Animal Law Section**
http://connect.michbar.org/animallaw/home/
- https://live-aldf-wp.pantheonsite.io/article/bar-association-animal-law-sections-and-committees/
- https://live-aldf-wp.pantheonsite.io/article/bar-association-animal-law-sections-and-committees/

**Back to Nature Wildlife Refuge**
http://www.btn-wildlife.org/
- https://live-aldf-wp.pantheonsite.io/article/barry-university-school-of-law-stepping-up-to-protect-animals/

**One Tail at a Time**
http://www.onetailatatime.org/
- https://live-aldf-wp.pantheonsite.io/article/chicago-kent-college-of-law-foie-gras-panel/

**describes Kittles history**
http://communities.justicetalking.org/blogs/day17/archive/2007/06/13/no-it-s-just-a-dog-animal-abuse-and-beyond.aspx
- https://live-aldf-wp.pantheonsite.io/case/animal-hoarding-case-study-vikki-kittles/

**Despite legal requirements**
http://awic.nal.usda.gov/alternatives/3rs
- https://live-aldf-wp.pantheonsite.io/focus-area/animals-used-in-research/
- https://live-aldf-wp.pantheonsite.io/focus_area/animals-used-in-research/
- https://live-aldf-wp.pantheonsite.io/focus_area/animals-used-in-research/380/

# Internal Links

**Contact Us**
https://live-aldf-wp.pantheonsite.io/about-us/contact-us/

- My dog was declared “Dangerous” or “vicious”
  http://live-aldf-wp.pantheonsite.io/resources/other-issues-regarding-your-companion-animal/what-to-do-if-your-dog-is-in-danger-of-being-declared-vicious-or-if-your-dog-has-bitten-someone-who-is-now-suing-you/
  - **Correct link:** /article/what-to-do-if-your-dog-is-in-danger-of-being-declared-vicious-or-if-your-dog-has-bitten-someone-who-is-now-suing-you/)
  - **Note:** Link should be added using WordPress link button in wysiwyg to prevent broken links in the future. We could also create a redirect for `resources/other-issues-regarding-your-companion-animal` to `articles/`.
- Custody battle over a companion animal
  https://live-aldf-wp.pantheonsite.io/resources/other-issues-regarding-your-companion-animal/what-to-do-if-you-are-involved-in-a-custody-battle-over-your-companion-animal/
- Improving animal protection laws
  https://live-aldf-wp.pantheonsite.io/resources/advocating-for-animals/

**2015 Canadian Animal Protection Laws Rankings**
https://live-aldf-wp.pantheonsite.io/article/2015-canadian-animal-protection-laws-rankings/
- This page was migrated from old site and has [custom bullets images](http://aldf.org/wp-content/uploads/img/pic/bullet.gif) that no longer exist on new site. I would suggest coding as a list.
- It also has numerous links to download files on the old site that may no longer work on the new site.

**2018 New Voices in Animal Law Writing Contest: Laurel Tallent**
https://live-aldf-wp.pantheonsite.io/article/2018-new-voices-in-animal-law-writing-contest-laurel-tallent/

- The jump links on this page use the full URL of the old site. They should just be the ID instead (e.g. `href="#jump_target"`)

**Advancement of Animal Law Scholarships**
http://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/

- “How to Apply” link is broken http://aldf.org/resources/animal-law-events-opportunities/opportunities/?id=31

**2010 Recipients of the ALDF Advancement of Animal Law Scholarship**
https://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/2010-recipients-of-the-aldf-advancement-of-animal-law-scholarship/

- “U.S. v. Stevens” link is broken https://live-aldf-wp.pantheonsite.io/article.php?id=1329

**2015 Advancement of Animal Law Scholarship Winners**
https://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/2015-advancement-of-animal-law-scholarship-winners/

- Meatless Mondays campaign http://aldf.org/about-us/saldf/chapter-spotlights/saldf-promotes-meatless-monday-tips-from-pace-law-schools-campaign/

**Comment by tedw** [comment]
Additional broken links:

Speak Out For Farmed Animals Week
https://live-aldf-wp.pantheonsite.io/article/save-the-date-for-speak-out-for-farmed-animals-week/
https://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/2015-advancement-of-animal-law-scholarship-winners/

Meatless Mondays
https://live-aldf-wp.pantheonsite.io/about-us/saldf/chapter-spotlights/saldf-promotes-meatless-monday-tips-from-pace-law-schools-campaign/
https://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/2016-advancement-of-animal-law-scholarship-winners/

Animal Law Program
https://live-aldf-wp.pantheonsite.io/about-us/programs/animal-law-program/
https://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/2016-advancement-of-animal-law-scholarship-winners/

animal legal issues
https://live-aldf-wp.pantheonsite.io/about-us/saldf/animal-law-101/
https://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/2016-advancement-of-animal-law-scholarship-winners/

Litigation Program
https://live-aldf-wp.pantheonsite.io/about-us/programs/litigation-program/
https://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/2016-advancement-of-animal-law-scholarship-winners/

opportunities
https://live-aldf-wp.pantheonsite.io/resources/law-professional-law-student-resources/law-students-saldf-chapters/opportunities-in-animal-law/
https://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/2016-advancement-of-animal-law-scholarship-winners/

Criminal Justice Program
https://live-aldf-wp.pantheonsite.io/about-us/programs/criminal-justice-program/
https://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/2016-advancement-of-animal-law-scholarship-winners/

cage-free eggs to her campus
https://live-aldf-wp.pantheonsite.io/about-us/saldf/chapter-spotlights/boston-college-law-school-cage-free-egg-campaign/
https://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/2016-advancement-of-animal-law-scholarship-winners/

regional representative
https://live-aldf-wp.pantheonsite.io/resources/animal-law-events-opportunities/opportunities/?id=2306
https://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/2016-advancement-of-animal-law-scholarship-winners/

WCL SALDF chapter
https://www.wcl.american.edu/org/animallaw/
https://live-aldf-wp.pantheonsite.io/article/advancement-of-animal-law-scholarships/2016-advancement-of-animal-law-scholarship-winners/

first animal law dean
https://live-aldf-wp.pantheonsite.io/?p=25606
https://live-aldf-wp.pantheonsite.io/article/aldf-ll-m-scholar-award/

Student Animal Legal Defense Fund
https://live-aldf-wp.pantheonsite.io/?p=24573
https://live-aldf-wp.pantheonsite.io/article/aldf-ll-m-scholar-award/

Animal abuse registry approved in Hillsborough County barring abusers from adoption http://www.tampabay.com/blogs/baybuzz/animal-abuse-registry-approved-in-hillsborough-county-barring-abusers-from/2292727
https://live-aldf-wp.pantheonsite.io/article/animal-abuser-registry-created-in-florida-county/

Working With Legislators
https://live-aldf-wp.pantheonsite.io/article.php?id=263
https://live-aldf-wp.pantheonsite.io/article/animal-cruelty-and-domestic-violence/

Michael Vick dogfighting case
https://live-aldf-wp.pantheonsite.io/article.php?id=928
https://live-aldf-wp.pantheonsite.io/article/animal-fighting-facts/

Each state has its own court rules
https://live-aldf-wp.pantheonsite.io/wp-content/uploads/downloads/special_masters_state_chart2008.pdf
https://live-aldf-wp.pantheonsite.io/article/animal-fighting-facts/

roosters
https://live-aldf-wp.pantheonsite.io/wp-content/uploads/2018/06/GettyImages-478621957-320x180.jpg
https://live-aldf-wp.pantheonsite.io/article/animal-fighting-facts/animal-fighting-federal-law/

Animal Protection Laws of the United States of America, Second Edition
https://live-aldf-wp.pantheonsite.io/article.php?id=259
https://live-aldf-wp.pantheonsite.io/article/animal-fighting-facts/animal-fighting-state-laws/

recommended amendment
https://live-aldf-wp.pantheonsite.io/article.php?id=460
https://live-aldf-wp.pantheonsite.io/article/animal-fighting-facts/animal-fighting-state-laws/

Animal Legal Defense Fund Student Convention
https://live-aldf-wp.pantheonsite.io/animal-legal-defense-fund-student-conventions/
https://live-aldf-wp.pantheonsite.io/article/animal-law-101/

summer program
https://law.lclark.edu/centers/animal_law_studies/curriculum/course_descriptions/summer/
https://live-aldf-wp.pantheonsite.io/article/animal-law-101/

Animal Law Certificate
https://law.lclark.edu/centers/animal_law_studies/curriculum/specialization/
https://live-aldf-wp.pantheonsite.io/article/animal-law-101/

Canadian Perspectives on Animals and the Law
https://live-aldf-wp.pantheonsite.io/resources/law-professional-law-student-resources/law-students-saldf-chapters/animal-law-books-periodicals/aldf.org/wp-admin/post.php?post=24549&action=edit
https://live-aldf-wp.pantheonsite.io/article/animal-law-books-periodicals/

Federal Wildlife Laws
https://www.animallaw.info/policy/pobofedwildpromo.htm
https://live-aldf-wp.pantheonsite.io/article/animal-law-books-periodicals/

An Introduction to Animals and the Law
https://us.macmillan.com/anintroductiontoanimalsandthelaw/JoanSchaffner
https://live-aldf-wp.pantheonsite.io/article/animal-law-books-periodicals/

Animal Law: Welfare, Interests, and Rights http://www.aspenpublishers.com/Product.asp?catalog_name=Aspen&product_id=1454802669&utm_source=Google&utm_medium=Search&utm_campaign=GoogleProductSearch&cookie_test=1
https://live-aldf-wp.pantheonsite.io/article/animal-law-books-periodicals/

Animal Liberation
https://www.harpercollins.com/books/Animal-Liberation-Peter-Singer?isbn=9780061711305&HCHP=TB_Animal+Liberation
https://live-aldf-wp.pantheonsite.io/article/animal-law-books-periodicals/

Rattling the Cage: Towards Legal Rights for Animals
https://www.perseusbooks.com/perseus/book_detail.jsp?isbn=0738204374
https://live-aldf-wp.pantheonsite.io/article/animal-law-books-periodicals/

“Groups Sue Feds for Putting Whales and Dolphins in Crosshairs throughout Southern California and Hawaiian Waters.”
https://live-aldf-wp.pantheonsite.io/?p=45946
https://live-aldf-wp.pantheonsite.io/article/appeals-court-rules-u-s-navy-sonar-use-violates-marine-mammal-protection-act/

The Law Society of New South Wales, Young Lawyers Animal Law Committee
https://www.lawsociety.com.au/about/YoungLawyers/Committees/AnimalLaw/index.htm
https://live-aldf-wp.pantheonsite.io/article/bar-association-animal-law-sections-and-committees/

18th Annual Animal Law Conference http://law.lclark.edu/centers/animal_law_studies/events/animal_law_conference/current/program/
https://live-aldf-wp.pantheonsite.io/article/barry-university-school-of-law-stepping-up-to-protect-animals/

West Hollywood Fur Ban Information http://www.weho.org/city-hall/city-departments/public-works/code-compliance/fur-ban
https://live-aldf-wp.pantheonsite.io/article/berkeley-california-becomes-second-u-s-city-to-ban-sale-of-fur-clothing/

aldf.org/compendium
https://live-aldf-wp.pantheonsite.io/resources/advocating-for-animals/animal-protection-laws-of-the-united-states-of-america-and-canada/
https://live-aldf-wp.pantheonsite.io/article/best-worst-states-animal-protection-laws-2017-report-released/

rulemaking
https://live-aldf-wp.pantheonsite.io/article/press-releases/aldf-petitions-california-to-regulate-greenhouse-emissions-from-animal-agriculture/
https://live-aldf-wp.pantheonsite.io/article/california-proposing-regulation-and-mandatory-reporting-of-greenhouse-gas-emissions-from-animal-agriculture/

pending cases
https://live-aldf-wp.pantheonsite.io/cases-campaigns/timelines/ag-gag/
https://live-aldf-wp.pantheonsite.io/article/canadian-activist-acquitted-of-criminal-charges-for-giving-water-to-thirsty-pigs-bound-for-slaughter/

cruel rodeo industry
https://live-aldf-wp.pantheonsite.io/cases-campaigns/features/rodeo-facts-the-case-against-rodeos/
https://live-aldf-wp.pantheonsite.io/article/canadian-saldf-chapters-challenge-quebec-rodeos/

here.
https://live-aldf-wp.pantheonsite.io/resources/law-professional-law-student-resources/law-students-saldf-chapters/saldf-project-grants/
https://live-aldf-wp.pantheonsite.io/article/canadian-saldf-chapters-challenge-quebec-rodeos/

Proposition 2
https://live-aldf-wp.pantheonsite.io/article/chapman-university-school-of-law-raising-funds-and-awareness-for-animals/article.php?id=757
https://live-aldf-wp.pantheonsite.io/article/chapman-university-school-of-law-raising-funds-and-awareness-for-animals/

Animal Free
https://itunes.apple.com/us/app/animal-free/id357422989?mt=8
https://live-aldf-wp.pantheonsite.io/article/cruelty-free-guide/plant-based-kitchens/

Click here
https://play.google.com/store/apps/details?id=com.symbiotic.animalfree
https://live-aldf-wp.pantheonsite.io/article/cruelty-free-guide/plant-based-kitchens/

Vegan List
https://play.google.com/store/apps/details?id=io.appery.project144230
https://live-aldf-wp.pantheonsite.io/article/cruelty-free-guide/plant-based-kitchens/

Trader Joe’s
https://www.traderjoes.com/pdf/lists/list-vegan.pdf
https://live-aldf-wp.pantheonsite.io/article/cruelty-free-guide/plant-based-kitchens/

http://www.humanesociety.org/about/employment/jobs/public-policy-specialist-1.html?credit=web_id86441259
https://live-aldf-wp.pantheonsite.io/article/employment-opportunities/entry/6975

Farmed Animals and the Law
https://live-aldf-wp.pantheonsite.io/resources/advocating-for-animals/farmed-animals-and-the-law/
https://live-aldf-wp.pantheonsite.io/article/federal-appeals-court-dismisses-challenge-to-california-sales-ban-on-eggs-sourced-from-extreme-confinement-of-hens/

Medlen v. Strickland
https://live-aldf-wp.pantheonsite.io/article.php?id=2294
https://live-aldf-wp.pantheonsite.io/article/fran-ortiz/

companion animals are more than inanimate property
https://live-aldf-wp.pantheonsite.io/article.php?id=2199
https://live-aldf-wp.pantheonsite.io/article/fran-ortiz/

ALDF Attorney Member Spotlights
https://live-aldf-wp.pantheonsite.io/resources/law-professional-law-student-resources/aldf-attorney-member-spotlight/
https://live-aldf-wp.pantheonsite.io/article/how-legal-professionals-can-get-involved-in-animal-law/

Judge: Idaho’s Anti-Dairy Spying Law Is Unconstitutional
https://www.nytimes.com/aponline/2015/08/03/us/ap-us-dairy-spying-lawsuit.html?_r=0
https://live-aldf-wp.pantheonsite.io/article/in-the-news/

Activists Take a Stand for Embattled Zoo’s Lions http://files.courthousenews.com/2016/07/12/activists-take-a-stand-for-embattled-zoos-lions.htm
https://live-aldf-wp.pantheonsite.io/article/in-the-news/

Group Wants Peek at Foster Farms’ Water Bill http://files.courthousenews.com/2016/05/04/group-wants-peek-at-foster-farms-water-bill.htm
https://live-aldf-wp.pantheonsite.io/article/in-the-news/

Fight Over Lucky the Elephant Continues http://files.courthousenews.com/2016/02/01/fight-over-lucky-the-elephant-continues.htm
https://live-aldf-wp.pantheonsite.io/article/in-the-news/

Orca ‘Lolita’ at Miami facility to get endangered protection
https://www.sfchronicle.com/news/article/Orca-Lolita-at-Miami-facility-to-get-endangered-6063009.php 410 Gone
https://live-aldf-wp.pantheonsite.io/article/in-the-news/

Iowa zoo settles lawsuit; lions sent to Colorado sanctuary
https://www.yahoo.com/news/iowa-zoo-settles-lawsuit-lions-sent-colorado-sanctuary-133533480.html
https://live-aldf-wp.pantheonsite.io/article/in-the-news/

Wisconsin officials sued over hunter harassment law http://www.startribune.com/politics/national/435656733.html
https://live-aldf-wp.pantheonsite.io/article/in-the-news/

Animal Welfare Activists, State Spar Over ‘Ag-Gag’ Law
https://www.sanluisobispo.com/news/business/article81111357.html
https://live-aldf-wp.pantheonsite.io/article/in-the-news/

Tyson Foods Under Fire As Second Video Shows Chicken Abuse
https://www.foxbusiness.com/industries/2015/09/14/tyson-foods-under-fire-as-second-farm-is-accused-abuse/
https://live-aldf-wp.pantheonsite.io/article/in-the-news/

Animal Legal Defense Fund files new complaint against Hendry County monkey farm
https://www.naplesnews.com/errors/404/
https://live-aldf-wp.pantheonsite.io/article/in-the-news/

Kentucky Ranked Last in Animal Welfare Laws for 7th http://www.wbko.com/home/headlines/Kentucky-Ranked-last-in-Animal-Welfare-Laws-For-7th-Year-291331611.html
https://live-aldf-wp.pantheonsite.io/article/in-the-news/

Cat Haven agrees to add safety measures following lion mauling death
https://www.fresnobee.com/2015/01/13/4328791_cat-haven-agrees-to-improve-safety.html?rh=1
https://live-aldf-wp.pantheonsite.io/article/in-the-news/

Register today
https://live-aldf-wp.pantheonsite.io/resources/animal-law-events-opportunities/events/?id=2419
https://live-aldf-wp.pantheonsite.io/article/join-us-at-the-2016-animal-rights-national-conference/

attorney member update form
https://live-aldf-wp.pantheonsite.io/article/attorney-member-update-form/
https://live-aldf-wp.pantheonsite.io/article/law-professionals/

**Comment by lizzycederberg** [comment]
I sent a report of all the external links to the client. David is working on setting up redirects for internal broken links, so no further action needed on our end here.
