### ISSUE TITLE
Alert Promotion

### ISSUE THREAD

**Issue by cmontwill** [Threespot/aldf-wp#218]
@tedw....Despite the alert promotion being turned off on the backend its still showing up on our browsers...
https://live-aldf-wp.pantheonsite.io/
![screen shot 2018-07-13 at 7 43 55 pm](https://user-images.githubusercontent.com/5890745/42718208-1a6b85e0-86d5-11e8-97f2-61268a7dfd31.png)

Can you confirm this is not a caching issue? I've tested it on safari (which I never use) and there is not donation promo showing up. 

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Turn out we never integrated the on/off toggle 😬 Thankfully, that’s the easiest part of the donation toggle. Will be fixed momentarily.

**Comment by tedw** [comment]
Deploying now…

**Comment by tedw** [comment]
Deployed
