### ISSUE TITLE
Password protected publishing doesn't work

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#221]
ALDF needs to password protect this page so only internal users can see it, but when I turn the password on, I'm able to get to the page without it asking for a password (I'm in a different browser where I'm not logged into the CMS): https://aldf.org/project/animal-legal-defense-fund-style-guide/

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
I can confirm that password protection does not seem to be working. Will investigate.

**Comment by tedw** [comment]
Fixed, can test on https://test-aldf-wp.pantheonsite.io/project/animal-legal-defense-fund-style-guide/ (pw is `aldf`)

**Comment by tedw** [comment]
Fixed

**Comment by lizzycederberg** [comment]
@tedw I'm able to see the page without a password

**Comment by tedw** [comment]
![inconceivable](https://user-images.githubusercontent.com/864716/42783690-b8543044-891a-11e8-905c-082ec85aadb9.gif)

**Comment by tedw** [comment]
Ready for testing on prod https://aldf.org/project/animal-legal-defense-fund-style-guide/

**Comment by lizzycederberg** [comment]
Working now!
