### ISSUE TITLE
Add support@aldf.org as site admin

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#222]
@tedw Is it ok that this is a directory email? i.e. it goes to lots of people.

**Comment by tedw** [comment]
It’s up to them, but I think it makes sense to have this be a separate mailbox so people don’t get spammed with password reset emails and whatnot. This email could also be used for Mailgun, WooCommerce, and other 3rd-party services.

If their tech team isn’t able to setup a shared mailbox, we can just have it go to David or Elizabeth.

**Comment by lizzycederberg** [comment]
@tedw Let's go ahead an use this for now and we can change it if it's too much email. They don't want to have to check a separate inbox and this already goes to both of them plus a couple other people. Thanks!

**Comment by tedw** [comment]
Updated, they should receive a confirmation email.

**Comment by lizzycederberg** [comment]
Cool thanks!
