### ISSUE TITLE
Advice for finding old pages?

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#223]
@tedw David is trying to figure out what page to direct some old URLs to that didn't have redirects set up previously. He can't access those URLs anymore, though, so he's not sure exactly what content is on them. Any advice for finding those? I suggested Way Bak Machine 🤷‍♀️

**Comment by tedw** [comment]
Yeah, https://web.archive.org is his best bet.

Do they still have access to the old site? They should save a backup before shutting down the account.
