### ISSUE TITLE
Homepage: Article shows twice on mobile

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#225]
@tedw This article is appearing twice on the homepage, but only when you view it on mobile. 

![screen shot 2018-07-17 at 9 32 12 am](https://user-images.githubusercontent.com/13699106/42820537-6b7aecba-89a4-11e8-877c-ece65e89084f.png)

I also noticed that the first instance says "Companion Animals" and second says "Press Release". Please check.

![screen shot 2018-07-17 at 9 32 21 am](https://user-images.githubusercontent.com/13699106/42820522-62255d30-89a4-11e8-912e-e0690e322370.png)

cc @cmontwill 

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment]
Fixed

**Comment by lizzycederberg** [comment]
Looks good!
