### ISSUE TITLE
Image sizing- original checkbox

### ISSUE THREAD

**Issue by cmontwill** [Threespot/aldf-wp#233]
@tedw 
Site wide, we're having difficultly inserting non-standard aspect ratio imagery as well as imagery that doesn't meet the small or medium sized categories. This is coming up in cases of logos, banners and magazine covers. Images like this one: 
https://aldf.org/wp/wp-admin/upload.php?item=10531

While we could create a component to meet all these exact needs, it seems like the best way to deal with these edge cases is to allow editors to insert images at their original upload size. I realize there is a custom field in there for them, but on the back end, its hard to have to back and forth on these to get the right dimensions.

I do want to prevent them from using this all the time, so here are some suggestions for the label, open to others....

Original size (Unoptimized)
Unformatted original size
Thumbnail (<---- i know tricky)

**Comment by tedw** [comment]
@cmontwill Can you send me an example of a page where this is an issue?

FYI, images inserted via the wysiwyg editor are not subject to a fixed aspect ratio.

**Comment by cmontwill** [comment]
From EP...

https://aldf.org/article/student-animal-legal-defense-fund-saldf-program-guides/2018-2020-farmed-animals-the-law/

 

I uploaded the attached photo to put on this page.

When I uploaded it, it only gives me the option to make it small.

I think have to insert the image into the copy, then click edit on the image, then go in and add a custom size (which is the original size).

 @ted

**Comment by tedw** [comment]
I added “Original Size” to the image size menu.

>_With great power comes great responsibility._

**Comment by lizzycederberg** [comment]
Confirmed by Elizabeth via email on 8/9
