### ISSUE TITLE
CMS is slow

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#236]
CMS is super slow. David reported that the edit page load times are very slow, and I've noticed it too. Any recommendations?

**Comment by tedw** [comment]
This is primarily due to the way WordPress works and all of the various plugins. I don't know of anything we can do about it off hand but will ask around.

**Comment by tedw** [comment]
Yoast seems to be the main culprit. Disabling it prevents ~70 requests totaling ~2.7 MB. Load time with Yoast was a whopping 38 sec, but went down to 4 sec without Yoast.

**Comment by lizzycederberg** [comment]
Nothing to be done here right now. Thanks!
