### ISSUE TITLE
CSS issue on Email to Target EN pages

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#237]
It looks like there might be a CSS conflict with the EN wrapper that you developed for us.

On “email to target” pages, the Other Ways to Give and Footer get messed up. This **doesn’t** happen on other “petition” type pages.

Here’s an example: https://act.aldf.org/page/5509/action/1

![image001](https://user-images.githubusercontent.com/13699106/43486252-547fd6c2-94e1-11e8-8dce-217c2b7b1977.jpg)

**Comment by tedw** [comment]
Looks like the links in the footer are inheriting the body copy link styles.

**Comment by tedw** [comment]
The footer code is in the wrong place, it should be after `<main class="Main" id="main" role="main">` not inside of it. I suspect he made a new template but messed something up.

**Comment by lizzycederberg** [comment]
@tedw Is it something you can fix by updating this template? Like would the changes roll out to the forms he's already made?

**Comment by tedw** [comment]
Ok, figured it out. There was a missing line in the template code, but for some reason this was only a problem on that particular greyhound page, so we never noticed it during QA. It’s fixed now.

**Comment by lizzycederberg** [comment]
Thanks!
