### ISSUE TITLE
Map to migrate

### ISSUE THREAD

**Issue by rmundstock** [Threespot/aldf-wp#36]
http://aldf.org/resources/advocating-for-animals/animal-protection-laws-of-the-united-states-of-america-and-canada/

`<iframe src="/wp-content/themes/aldf/compendium-map/ca/map.html" frameallowfullscreen=""></iframe>`

**Comment by lizzycederberg** [comment]
@tedw we need to add this map to a page: https://live-aldf-wp.pantheonsite.io/article/animal-law-courses/

Please let me know if you need anything from ALDF for this.

**Comment by tedw** [comment]
The maps (Canada & U.S.) are separate iframes of custom pages on the old site, each linking to numerous custom assets. It is going to take 2–4 hrs to migrate this to the new site.

ALDF needs to copy over the PDFs to the new site:
e.g. http://aldf.org/wp-content/uploads/compendium-map/2017/usa/MICHIGAN.pdf

**Comment by tedw** [comment]
Map has been migrated but we still need ALDF to migrate the PDFs and then I need to update the links.

**Comment by tedw** [comment]
FYI, in order to make this happen I had to add a new “Custom HTML” page builder component. When pasting the code into the body copy WYSIWYG the map SVG code was breaking.

**Comment by lizzycederberg** [comment]
@tedw All of the PDF have been uploaded to `Documents/State Rankings` in the CMS. Do you need anything else to get those hooked up?

**Comment by lizzycederberg** [comment]
I'm going to see if I can take care of this one!

**Comment by lizzycederberg** [comment]
Ok well that was a failure -- I thought I would be able to replace the links to the PDFs in the HTML but I'm not seeing them. 

@tedw If there is a way for me to manually update these, please let me know so I can take this off your plate. 

Here's the page: https://live-aldf-wp.pantheonsite.io/article/animal-protection-laws-of-the-united-states-of-america/

Thanks!

**Comment by tedw** [comment]
This is where the PDF paths are defined:

USA
https://github.com/Threespot/aldf-wp/blob/master/web/wp-content/themes/aldf/resources/assets/maps/usa/map-config.js

Canada
https://github.com/Threespot/aldf-wp/blob/master/web/wp-content/themes/aldf/resources/assets/maps/canada/map-config.js

**Comment by lizzycederberg** [comment]
@tedw The new PDF paths follow this pattern `/wp-content/uploads/2018/06/WYOMING.pdf`

They are located in Media Library > Documents > State Rankings

**Comment by tedw** [comment]
Updated for U.S.A.
https://test-aldf-wp.pantheonsite.io/article/animal-protection-laws-of-the-united-states-of-america/

But looks like ALDF never uploaded the Canadian PDFs
https://test-aldf-wp.pantheonsite.io/article/animal-protection-laws-of-canada/

**Comment by lizzycederberg** [comment]
@tedw Canadian map PDFs are in Media Library > Document > Canada Rankings

**Comment by lizott** [comment]
@tedw similar to the other friday task - can you provide an update?

**Comment by tedw** [comment]
Updated

**Comment by cmontwill** [comment]
@tedw can you get this PDF to link for Nefoundland?
https://live-aldf-wp.pantheonsite.io/article/animal-protection-laws-of-canada/

https://live-aldf-wp.pantheonsite.io/wp-content/uploads/2018/07/Animal-Protection-Laws-of-Newfoundland-2017.pdf

**Comment by tedw** [comment]
Ugh, they changed the filename, deploying…
