### ISSUE TITLE
Add filter on Article listing page in CMS

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#37]
@tedw @matbrady David asked if we can add a filter to the Article listing page in the CMS to filter by article type. Not sure if this is easily doable -- please let me know.

https://live-aldf-wp.pantheonsite.io/wp/wp-admin/edit.php?post_type=article

**Comment by tedw** [comment]
Yes, we can do this but we should think about which filters we want on each content type. We should also think about what additional columns would make sense to display for each content type.

**Comment by rmundstock** [comment]
Article and Cases may be the only content types that need an additional filter since the will have the most content. I don't think there will be enough projects or issues, but it might be a good idea to confirm that with David.

Article, add filter by article type
Cases, add filter by work type

**Comment by lizzycederberg** [comment]
Looks good to me -- @tedw Please add Rachel's suggestions.

**Comment by tedw** [comment]
Updated. I also added a "Focus Area" column to both since I thought it would be useful.

**Comment by lizzycederberg** [comment]
This is awesome -- I especially like the counts of each that show. Thanks!
