### ISSUE TITLE
Solution for migrating in-line links

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#38]
@tedw @matbrady David mentioned that they were unsure of the best way to migrate content that includes links to pages on their current site since those links will all be pointing to old URLs once we go live. Do you have a recommendation for this? Anything we could do programmatically before launch? I told him we could give them a link scan report, but that would still be a ton of manual work. I also mentioned that if redirects are set up they will still go to the right place, but not ideal.

**Comment by tedw** [comment]
We can create redirect rules for content in subdirectories:

For example:
`http://aldf.org/blog/*`
`http://aldf.org/press-room/*`

Would redirect to
`https://aldf.org/article/*`

However, content that does not live in a subfolder will need its own redirect rule, for example:
`http://aldf.org/animals-so-much-more-than-property/`

New link would be
`https://aldf.org/article/animals-so-much-more-than-property/`

**Comment by rmundstock** [comment]
@lizzycederberg just need to re-iterate that if we go with this option they cannot edit the titles, they must remain the same as they are on the current site

**Comment by lizzycederberg** [comment]
Thank you both!

**Comment by lizzycederberg** [comment]
@tedw No action needed here. They removed all the links in the content and will be readding them as needed
