### ISSUE TITLE
Solution for migrating inline images

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#39]
Similar to #38 David also asked how they should migrate images that are in content. Seems like this needs to be a manual process, but he wants to know if there's a way to move over all their current images and retain folder structures and placement in legacy content. Any recommendations?

**Comment by tedw** [comment]
I think the only solution for images that are stored in custom folders (i.e. not in default `/year/month/` folders) is to copy those folders to the new site via FTP. We will need FTP access to their current site to do this.

**Comment by lizzycederberg** [comment]
Thanks!

**Comment by lizzycederberg** [comment]
@tedw We don't need to worry about this anymore -- they are manually migrating all images
