### ISSUE TITLE
Adjust timeline controls 

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#43]
- The "View" label should be Untitled Serif instead of Helvetica
- The default view is "Key Dates," so the "Key Dates" label should be dark orange with an underline. 

Design
![image](https://user-images.githubusercontent.com/6118778/40197833-93651f9e-59e2-11e8-9c1d-ec9a93e8adf5.png)

Dev
![image](https://user-images.githubusercontent.com/6118778/40197771-608a3cc6-59e2-11e8-8d85-863aed76349d.png)

https://live-aldf-wp.pantheonsite.io/case/kristen-lindsey/

https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/

**Comment by tedw** [comment]
I adjusted the styles because we need inactive, inactive hover, active, and active hover styles. CC: @lfhello

**Comment by jamielyn** [comment]
:bear:
