### ISSUE TITLE
Related News adjustments 

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#44]
https://live-aldf-wp.pantheonsite.io/case/kristen-lindsey/
https://live-aldf-wp.pantheonsite.io/issue/ag-gag/

- "Related News" heading is missing 
- There should be a minimum of 30px between content items. There's only 20px between the two stories in the right column. This applies to both desktop and mobile. 
- Remove the content type to the right of the date on each item. The content type should only appear in the single column listing, not the two column grid
- "See more" button is missing

Dev
![image](https://user-images.githubusercontent.com/6118778/40197959-fe9b08aa-59e2-11e8-94da-b77bf289a210.png)

Design
![image](https://user-images.githubusercontent.com/6118778/40197946-f6e304d2-59e2-11e8-8403-48181a654bfb.png)

**Comment by rmundstock** [comment]
@tedw updated test issue page to include related news items with images;

https://live-aldf-wp.pantheonsite.io/issue/ag-gag/

Largest news item does not show an image, even when a featured image is present in the article

![screen shot 2018-05-21 at 8 18 34 am](https://user-images.githubusercontent.com/5369002/40315211-955848cc-5ccf-11e8-926b-98ba622a01a8.png)

**Comment by tedw** [comment]
I think these issues have all been previously addressed. Can you all please take a look?

**Comment by jamielyn** [comment]
On tablet/mobile, the 1px rules are orange. Please change the color to gray so they match the other listing rules.

1px solid rgba(74,61,49,.5)

![image](https://user-images.githubusercontent.com/6118778/40854667-26f13298-65a0-11e8-8719-414d9456addc.png)

**Comment by tedw** [comment]
This was something Laura and I discussed during development.

@lfhello please advise

**Comment by lfhello** [comment]
@tedw 
yes, we decided to make them all the thin yellow on mobile so they are equal and not distracting- thanks for checking in
