### ISSUE TITLE
Full width pull quote adjustments 

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#45]
Lower the opacity of the background image to 20%

Dev
![image](https://user-images.githubusercontent.com/6118778/40198191-a93b4202-59e3-11e8-8c3a-fd9eb185ba65.png)

Desired design 
![image](https://user-images.githubusercontent.com/6118778/40198178-a1fde5f8-59e3-11e8-8dba-12b9fe7e0dc2.png)

https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/

**Comment by tedw** [comment]
Where do you see 20% in the Sketch file? The homepage has the opacity set ~80%, which I assume is what Mat went off of.

![screen shot 2018-05-21 at 3 50 20 pm](https://user-images.githubusercontent.com/864716/40326865-cffb6cfe-5d0e-11e8-8f0f-0dba0e10a11d.png)

**Comment by jamielyn** [comment]
@tedw I was going off of the designs in InVision and adjusted the opacity in the dev tools to 20% to match the design. @lfhello can advise further on intended styling.

**Comment by lfhello** [comment]
@tedw Hi Ted, yes, I've tried it at both opacities- this is on me and not any of you!

I think 20% is closer to what I was wanting- so that the type stands out more and the landscape takes a backseat. 

Thanks

**Comment by jamielyn** [comment]
:horse:
