### ISSUE TITLE
Action strata adjustments 

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#47]
* Missing “Actions” shield 
* Theres should be about 60px between the red rule and the first action promo 
* The large image should be left aligned with the red rule and action below 

Dev 
![image](https://user-images.githubusercontent.com/6118778/40198362-45c7ac14-59e4-11e8-9aa5-f68af99b3776.png)

Design 
![image](https://user-images.githubusercontent.com/6118778/40198378-4db9aecc-59e4-11e8-8aa8-63eb5e5570c3.png)

https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/
https://live-aldf-wp.pantheonsite.io/issue/ag-gag/

**Comment by tedw** [comment]
I think this was incomplete when you reviewed it, looks good now.

**Comment by jamielyn** [comment]
:white_check_mark:
