### ISSUE TITLE
Action promo image adjustments 

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#48]
* The red shield on hover is a little harsh. Please change the color back to white on hover and lower the opacity of the shield to 50%
* The stroke of the shield gets thicker on smaller breakpoints. Can we adjust, so the width is always 5px?

Hover in dev 
![image](https://user-images.githubusercontent.com/6118778/40198578-d44e06d6-59e4-11e8-9714-ea558bc64175.png)

Shield on mobile 
![image](https://user-images.githubusercontent.com/6118778/40198595-df44492e-59e4-11e8-89ba-c6571a6f7021.png)

**Comment by tedw** [comment]
Update deployed.

FYI, the thicker shield is what was designed for mobile so I left it. Did you run this by Monte/Laura?

**Comment by jamielyn** [comment]
The hover looks good. @lfhello and I discussed the stroke width before I filed this ticket. Reassigning so you two can discuss further.

**Comment by tedw** [comment]
Ok cool, will update, just wanted to make sure you had seen the mobile comp :)

**Comment by jamielyn** [comment]
:cat2:
