### ISSUE TITLE
Make tooltip corners square

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#49]
Dev
![image](https://user-images.githubusercontent.com/6118778/40198684-1f04f3ba-59e5-11e8-9f0d-ee7a163cf88f.png)

Design 
![image](https://user-images.githubusercontent.com/6118778/40198677-1800730a-59e5-11e8-81b5-378747f844d8.png)

https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/

**Comment by tedw** [comment]
Updated

**Comment by jamielyn** [comment]
:heavy_check_mark:
