### ISSUE TITLE
Article: Date and social on mobile 

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#51]
- Adjust the order so the date appears above the social links
- Adjust spacing so there's at least 30px between the date and social links

Dev
![image](https://user-images.githubusercontent.com/6118778/40198973-0479fab2-59e6-11e8-9514-c152e41930e4.png)

https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/

**Comment by tedw** [comment]
Updated, measured 30px from baseline of date to cap height of “Share.” LMK if you want to measure to the vert rules instead.

**Comment by jamielyn** [comment]
:tiger:
