### ISSUE TITLE
Main nav VQA

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#54]
- Menu label and icon, and search label and icon should be #4a3d31 (it looks like they're black now)
- Increase size of donate heart icon, so it's about 30 x 30px
- When the menu is open, the close background should be #4a3d31
- Lower the opacity of the vertical divider rules slightly to soften 
- About ALDF, Legal Resources and Shop links should be bold

Dev
![image](https://user-images.githubusercontent.com/6118778/40200574-aabfcaf6-59ea-11e8-8665-f2166ee3ef89.png)

Design 
![image](https://user-images.githubusercontent.com/6118778/40200550-9c9cf688-59ea-11e8-9bd4-380e2ac6d8d4.png)

### Mobile

- The donate button should be below search 
- It looks like 1px of the page content is visible above the search field 

Dev
![image](https://user-images.githubusercontent.com/6118778/40201025-e7b51500-59eb-11e8-9a74-3732c2c121db.png)

Design 
![image](https://user-images.githubusercontent.com/6118778/40201059-01a9b452-59ec-11e8-9e20-2ecd931d124b.png)

**Comment by tedw** [comment]
@lfhello Didn’t we decide to put the donate button at the top?

**Comment by lfhello** [comment]
@tedw yes, we decided to move it up- Jamielyn was primarily looking at older InVision comps. 

I do feel like Search is getting lost at the bottom now and I'm wondering if we make Search brown like it is in the dropdown on desktop

![screen shot 2018-05-31 at 10 02 09 am](https://user-images.githubusercontent.com/17705791/40786724-c25b3928-64b9-11e8-83b0-b11f0a6bb9c3.png)

**Comment by tedw** [comment]
Updated

**Comment by jamielyn** [comment]
:poodle:
