### ISSUE TITLE
Issue Page: Expand text fade

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#56]
Around 2–4 lines of text should fade out above the Expand link. 

Dev
![image](https://user-images.githubusercontent.com/6118778/40202694-c1ee7f0a-59f0-11e8-8d03-eee5d6c6a3af.png)

Design
![image](https://user-images.githubusercontent.com/6118778/40202707-c8cee404-59f0-11e8-9c5a-bd9ac7a40084.png)

https://live-aldf-wp.pantheonsite.io/issue/ag-gag/

**Comment by tedw** [comment]
Mat fixed this

**Comment by jamielyn** [comment]
:cat:
