### ISSUE TITLE
Article: Increase title block subtitle font size 

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#58]
Increase subtitle to match subtitles on issue and case pages 
* Font-size: 22px
* Line-height: 29px

Dev
![image](https://user-images.githubusercontent.com/6118778/40243627-b783b65e-5a8e-11e8-97e4-7763df27c682.png)

Issue subtitle 
![image](https://user-images.githubusercontent.com/6118778/40243641-bf9f4484-5a8e-11e8-90fd-b4cff5a13221.png)

https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/

https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/test-for-grouping/

**Comment by tedw** [comment]
I think this was unfinished when you reviewed it, looks good now.

**Comment by jamielyn** [comment]
:dog:
