### ISSUE TITLE
No match search results need styling love

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#71]
https://live-aldf-wp.pantheonsite.io/search/sdfsdfsdf/

**Comment by tedw** [comment]
Search page is not ready for QA

**Comment by tedw** [comment]
Ready for testing now

Search
http://live-aldf-wp.pantheonsite.io/search/test/

Cases
http://live-aldf-wp.pantheonsite.io/cases/

Articles
http://live-aldf-wp.pantheonsite.io/articles/

Take Action (Actions)
http://live-aldf-wp.pantheonsite.io/take-action/

**Comment by lfrancis** [comment]
Confirmed addressed
