### ISSUE TITLE
Issues item listed in footer but not menu

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#72]
https://live-aldf-wp.pantheonsite.io/case/kristen-lindsey/

While the footer lists Issue: _Animals Used in Research_, the menu lists no issues.

**Comment by tedw** [comment]
The man nav code that populates the Focus Areas and How We Work types seems to be affected by some code on the case page. This only happens on case pages AFAIK.

**Comment by tedw** [comment]
Was due to conflicting variable names on the case page. Fixed now.

**Comment by lfrancis** [comment]
Confirmed addressed
