### ISSUE TITLE
Newsletter signup needs to be wired up

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#73]
https://live-aldf-wp.pantheonsite.io/case/kristen-lindsey/

**Comment by tedw** [comment]
@lizzycederberg We need this info from ALDF.

**Comment by tedw** [comment]
@lizzycederberg I need the form embed code, or instructions for how to find it in Engaging Networks.

**Comment by lizzycederberg** [comment]
@tedw David sent this: https://act.aldf.org/page/4644/subscribe/1

Is that what you need?

**Comment by tedw** [comment]
Sure, that will work. I guess the signup form will have to work like the donation form, where we pass the value to Engaging Networks via a URL param:

e.g. https://act.aldf.org/page/4644/subscribe/1?supporter.emailAddress=hello@threespot.com

We should probably add a URL field in the admin for this in case it ever changes. Same with the donation form now that I think about it.

This will take about an hour to do.

**Comment by lizzycederberg** [comment]
@tedw That sounds fine to me -- please proceed. Thanks

**Comment by tedw** [comment]
Newsletter form has been integrated.

**Comment by lizzycederberg** [comment]
Great! @lfrancis Can you please verify this is ok?

**Comment by lfrancis** [comment]
Confirmed addressed
