### ISSUE TITLE
Need favicon, apple icons

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#76]
https://live-aldf-wp.pantheonsite.io/case/kristen-lindsey/

**Comment by tedw** [comment]
@Henryhankdc I uploaded the icons the the meta tag HTML to use here:
https://github.com/Threespot/aldf-wp/tree/master/web/wp-content/themes/aldf/resources/assets/images/app-icons

**Comment by Henryhankdc** [comment]
added icons

**Comment by tedw** [comment]
@Henryhankdc I'm not seeing any of your commits, did you push to the remote branch?
https://github.com/Threespot/aldf-wp/commits/issue-76

**Comment by Henryhankdc** [comment]
@tedw no idea what happened there. Changes are part of the 404-page branch now.

**Comment by tedw** [comment]
Ready for review

**Comment by lfrancis** [comment]
Confirmed addressed
