### ISSUE TITLE
Action grid badge is MIA

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#79]
https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/

![mia](https://user-images.githubusercontent.com/6942589/40314458-8763a97a-5ce6-11e8-84b4-0c1884853a49.png)

**Comment by tedw** [comment]
Looks fine to me, is it still missing for you?

**Comment by lfrancis** [comment]
Still missing on all browsers

**Comment by tedw** [comment]
Ah, it's because the 1x image is missing but the 2x image is there, which is what I was seeing. Looks like the 1x image file name had a typo. Fixed now (a3fa42ee21d458b11c8cf1488c93d988b006347c).

**Comment by lfrancis** [comment]
Confirmed addressed
