### ISSUE TITLE
Article fails to validate

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#80]
https://validator.w3.org/nu/?doc=https%3A%2F%2Flive-aldf-wp.pantheonsite.io%2Farticle%2Ftest-article-with-components%2F

Unclosed elements, empty heading, etc.

**Comment by tedw** [comment]
Something seems amiss with the gallery images

**Comment by tedw** [comment]
The gallery images are lazy loaded and did not have a `src` attribute. I added an inline 1px transparent gif as the fallback. Still not sure where the unclosed `<span>` is coming from, code looks fine.

**Comment by tedw** [comment]
@Henryhankdc Can you check the code near each instance of `<span class="MetaRow-item">{{ get_the_date() }}</span>` to see if there is a syntax error?

**Comment by Henryhankdc** [comment]
@ted I think I found the extra `<span>`. Branch has been pushed for review.

**Comment by tedw** [comment]
Fixed now. Remaining errors/warning are either FOL (e.g. lazy-loaded images use `sizes` attribute without a `srcset` attribute, which is added with JS) or acceptable (e.g. redundant role attribute on HTML5 section elements).

**Comment by lfrancis** [comment]
Confirmed addressed
