### ISSUE TITLE
Need vertical white space to delineate subnav in mobile render

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#81]
https://live-aldf-wp.pantheonsite.io/article/test-article-with-components/

![spaceme](https://user-images.githubusercontent.com/6942589/40315029-4184f2f4-5ce8-11e8-8385-6a5976a23163.png)

**Comment by tedw** [comment]
Addressed by #57

**Comment by lfrancis** [comment]
Confirmed addressed
