### ISSUE TITLE
Donate interstitial stretched in IE11

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#83]
https://live-aldf-wp.pantheonsite.io

The aspect ratio of the Cheetahs are not preserved in IE11:

![ie11vsdonateinterstitial](https://user-images.githubusercontent.com/6942589/40316280-d5a425d8-5ceb-11e8-9ff5-440a812d10d6.png)

**Comment by tedw** [comment]
This is fixed now

**Comment by lfrancis** [comment]
Confirmed addressed
