### ISSUE TITLE
breakpoint

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#84]
https://live-aldf-wp.pantheonsite.io

News images show up on mobile but not desktop:

![breakpoint](https://user-images.githubusercontent.com/6942589/40316797-71741814-5ced-11e8-9692-4afcf1bf7b53.png)

**Comment by tedw** [comment]
I see them now, perhaps it was a caching issue.

**Comment by lfrancis** [comment]
Still seeing the missing images, high res images?

**Comment by tedw** [comment]
Was missing low-res images due to a typo, fixed now.
