### ISSUE TITLE
IE11 vs Issue header

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#85]
https://live-aldf-wp.pantheonsite.io/issue/ag-gag/

![ie11vsthe world](https://user-images.githubusercontent.com/6942589/40321024-b0fb1ef2-5cfb-11e8-9b85-5c5c14c9f261.png)

**Comment by tedw** [comment]
Fixed, awaiting deployment

**Comment by tedw** [comment]
Ready for testing

**Comment by lfrancis** [comment]
Confirmed addressed
