### ISSUE TITLE
People Header not indented on Safari-latest

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#86]
https://live-aldf-wp.pantheonsite.io/person/lorem-ipsum/

The People Header is not indented on Safari-latest, desktop or iOS, should it be?

![ievsindent](https://user-images.githubusercontent.com/6942589/40321690-e205c464-5cfd-11e8-9d06-5f20599ae350.png)

**Comment by tedw** [comment]
Fixed, awaiting deployment

**Comment by tedw** [comment]
Ready for testing

**Comment by lfrancis** [comment]
Confirmed addressed
