### ISSUE TITLE
Unexpected vertical space on Focus Area mobile render

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#87]
https://live-aldf-wp.pantheonsite.io/focus_area/farmed-animals/

Also seen on iOS

![extravertical](https://user-images.githubusercontent.com/6942589/40322098-3e3b36d2-5cff-11e8-926a-1031fa71e1d1.png)

**Comment by tedw** [comment]
Fixed, awaiting deployment

**Comment by lfrancis** [comment]
Confirmed addressed
