### ISSUE TITLE
IE11 vs. Focus Area billboard

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#88]
https://live-aldf-wp.pantheonsite.io/focus_area/farmed-animals/

Focus Area billboard is MIA on IE11:

![ievsfocusbillboard](https://user-images.githubusercontent.com/6942589/40322218-9ff56398-5cff-11e8-88ec-63d4ae770867.png)

**Comment by tedw** [comment]
Fix, awaiting deployment

**Comment by tedw** [comment]
Ready for testing

**Comment by lfrancis** [comment]
Confirmed addressed
