### ISSUE TITLE
Shop issues at mobile widths

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#89]
http://live-aldf-shop.pantheonsite.io

Footer and search field label goes away at mobile widths

![storevsmobile](https://user-images.githubusercontent.com/6942589/40322642-05ba7b4a-5d01-11e8-8344-70c13fc2e8ec.png)

**Comment by Henryhankdc** [comment]
@lfrancis Mobile nav button has had color change as per instruction of @jamielyn  via [aldf shop issue #3](https://github.com/Threespot/aldf-shop/issues/3) and the sticky footer issue has also been address via the task on [aldf shop issue #4 ](https://github.com/Threespot/aldf-shop/issues/4)

**Comment by lfrancis** [comment]
Confirmed addressed
