### ISSUE TITLE
Shop fails validation

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#90]
http://live-aldf-shop.pantheonsite.io

See report at:
https://validator.w3.org/nu/?doc=http%3A%2F%2Flive-aldf-shop.pantheonsite.io

**Comment by lfrancis** [comment]
Wow, something about this page actually causes SortSite to give up the ghost!

**Comment by tedw** [comment]
@Henryhankdc Can you please address the following issues? We can safely ignore the rest in that report.

**1. Update meta viewport tag to allow scaling**

Current 
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">`

Desired
`<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`

**2. Figure out why this link tag is unclosed**
`<a href="http://live-aldf-shop.pantheonsite.io/my-account/">My Acc`

**Comment by Henryhankdc** [comment]
@lfrancis and @tedw both 1 and 2 have been addressed.

**Comment by tedw** [comment]
@Henryhankdc Still seems to be an unclosed tag somewhere, see item 14 in the validation report:
https://validator.w3.org/nu/?doc=http%3A%2F%2Flive-aldf-shop.pantheonsite.io

**Comment by lfrancis** [comment]
Confirmed addressed
