### ISSUE TITLE
Safari-desktop lacks selected element block outline

### ISSUE THREAD

**Issue by lfrancis** [Threespot/aldf-wp#93]
http://live-aldf-shop.pantheonsite.io/product/aldf-womens-t-shirt/

First up is Safari-latest, second is FFX 54:

![outlined](https://user-images.githubusercontent.com/6942589/40325484-e2312b3e-5d09-11e8-9c77-20095b70158a.gif)

**Comment by Henryhankdc** [comment]
removed selected element block line on click using what-input.js library as per suggestion of @tedw. Selected element block line appears on tab, but not click.

**Comment by lfrancis** [comment]
Confirmed addressed
