### ISSUE TITLE
Person listing: Rule missing after each person

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#95]
https://live-aldf-wp.pantheonsite.io/people/

There should be a 1px rule after each person in the list. It's currently only appearing after the last person in the list. 

Dev
![image](https://user-images.githubusercontent.com/6118778/40373558-24605718-5db5-11e8-8d73-77149cb0e828.png)

![image](https://user-images.githubusercontent.com/6118778/40373569-2d14c7b8-5db5-11e8-8daf-51d2554eb2db.png)

**Comment by tedw** [comment]
This has since been changed to match the new content listing page styles. LMK if you want to make changes.

**Comment by jamielyn** [comment]
:monkey_face:
