### ISSUE TITLE
Person detail: H1 is indented 

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-wp#99]
https://live-aldf-wp.pantheonsite.io/person/lorem-ipsum/

The h1 is indented and should be Untitled Serif instead of Helvetica. 

Dev
![image](https://user-images.githubusercontent.com/6118778/40374735-a52234e6-5db7-11e8-8e71-2ab4973f4bb0.png)

Design
![image](https://user-images.githubusercontent.com/6118778/40374770-c02f2c76-5db7-11e8-8807-ee5485247e15.png)

**Comment by tedw** [comment]
This was previously fixed

**Comment by jamielyn** [comment]
Thanks, the spacing looks good. The h1 is set in Untitled Serif in the designs, not Helvetica. Did you and @lfhello talk about this change?

**Comment by tedw** [comment]
No, this was probably because Mat didn’t have Untitled Serif installed and thought it was supposed to be Helvetica :P

**Comment by lfhello** [comment]
Looks good!
